### PR TITLE
Subscribe to clock changes even if initial time is outside intervals.

### LINKED ISSUE #2924: WMS layers fail to display on first attempt
On http://terria-cube.terria.io/

1. Add a WMS layer (e.g. any layer under wms.datacube.org.au)
2. Nothing displays!!!
3. Click "remove all".
4. Repeat step 1.
5. Now the WMS layer displays correctly.

Can reproduce on http://nationalmap.gov.au e.g. using "my data->web data"

### PR DESCRIPTION
**Pull request by kring**
Fixes #2924

### CODE REVIEW

**Comment by kring** [comment]
@a-stacey can you please review and merge this?

**Comment by kring** [comment]
@SpacemanPaul this should fix your issue #2924. You can try it out here:
http://ci.terria.io/missing-subscription/

**Comment by SpacemanPaul** [comment]
Yep, that works for me.  Thanks, guys.

**Comment by a-stacey** [comment]
Looks good to me.

**Pull request merged**
