### PR TITLE
Location distance legend

### PR DESCRIPTION
**Pull request by chloeleichen**
Fixes: https://github.com/TerriaJS/terriajs/issues/2143

### CODE REVIEW

**Comment by kring** [comment]
I'll leave this one to yu @RacingTadpole.

**Comment by RacingTadpole** [comment]
Sure!

**Comment by RacingTadpole** [comment]
This is great, thanks @chloeleichen - just one thing - can you un-obscure the disclaimer again, per @kring's comment in #2143?

**Comment by chloeleichen** [comment]
now the legend doesn't block the disclaimer in all base-maps except for one: 
screen shot 2016-10-10 at 9 48 37 am

is this acceptable ?

**Comment by RacingTadpole** [comment]
Thanks! Doesn't the disclaimer height depend on the window's width though? Is there a way to float the lat/lon/elev box above the disclaimer regardless of its height?

**Comment by chloeleichen** [comment]
@RacingTadpole no they don't interfere with each other.

**Comment by RacingTadpole** [comment]
Sorry, I meant situations like this:
image
Although I see now that the live NationalMap does the same thing. @kring - what do you think?

**Comment by chloeleichen** [comment]
unfortunately the legend does not know by default how tall the disclaimer is. besides, there just isn't enough space for it.

**Comment by chloeleichen** [comment]
we could, however, move up the disclaimer and pin the legend to the bottom, let me have a try

**Comment by RacingTadpole** [comment]
Maybe... although the disclaimer is a lot wider than the lat/lon box, so it might be more annoying higher up.

**Comment by chloeleichen** [comment]
what about this? 
screen shot 2016-10-10 at 10 20 33 am

**Comment by RacingTadpole** [comment]
I think the lat/lon info should be higher priority than the disclaimer, so should be above it ... but happy to hear from @philipgrimmett or others.

**Comment by RacingTadpole** [comment]
Sorry @chloeleichen - I was too hasty merging that - there are three lint errors - could you please fix these (either in a new branch or direct in master)?

```
/home/travis/build/TerriaJS/terriajs/lib/ReactViews/DataCatalog/DataCatalogMember.jsx
  11:34  error  Component definition is missing display name  react/display-name
/home/travis/build/TerriaJS/terriajs/lib/ReactViews/Search/SearchBox.jsx
  14:34  error  Component definition is missing display name  react/display-name
/home/travis/build/TerriaJS/terriajs/lib/ReactViews/Search/SearchHeader.jsx
  7:34  error  Component definition is missing display name  react/display-name
```

**Comment by chloeleichen** [comment]
@RacingTadpole 
I tried to look it up and found this: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md

Tho i don't know why it only comes up now and only in those two files. Do you happen to know why?

Here is the PR anyway: https://github.com/TerriaJS/terriajs/pull/2157

**Pull request merged**
