### PR TITLE
Make timeseries autoplay optional, preserving existing autoplay behaviour.

### PR DESCRIPTION
**Pull request by meh9**

### CODE REVIEW

**Comment by kring** [comment]
@meh9 you said on slack that you need to fix a bug in this before we can merge it, right?

**Comment by meh9** [comment]
The problem I noticed and was attempting to fix was "skipping timeseries", but it turns out this is an existing problem and nothing caused by this PR.

Have logged the issue separately: https://github.com/TerriaJS/terriajs/issues/917

This PR should now be ready to merge.

**Comment by kring** [comment]
Ok, thanks.  One last question before merging: who is tsimon?

**Comment by meh9** [comment]
tsimon is Travis here in Canberra, he's also on our Slack.

**Pull request merged**
