### PR TITLE
Apply dateFormat to date/time picker and time control

### LINKED ISSUE #3235: When the timeline has a date format, apply it to date picker and time control as well
When the timeline has a date format, apply it to date picker and time control as well.

E.g. this: https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/custodian/Institute_for_Sustainable_Futures/DANCE3/aremi-isf/constraints/ejs/constraints.ejs#L25

Shows up as this:

screen shot 2019-03-04 at 09 30 24

And we should apply the templated date `currentTime` to the date picker and time control as well - or alternatively a new format property in the init file so that we can exclude the `Year: ` part of it.

### PR DESCRIPTION
**Pull request by reginapramesti**
Fixes #3235 (and #2752)

### CODE REVIEW

**Comment by kring** [comment]
Looks good @reginapramesti! Can you please do two things:
* Update CHANGES.md
* Add/modify a file in wwwroot/test/init that we can use to try this out without creating our own init file.

**Comment by reginapramesti** [comment]
@kring I needed to modify the `regionMapping.json` file to get the vector tiles for the test datasets - not sure if that's the right way to do it?

**Comment by kring** [comment]
> I needed to modify the regionMapping.json file to get the vector tiles for the test datasets - not sure if that's the right way to do it?

If that dataset isn't suitable for inclusion in a TerriaJS test file (because of missing regions or any other reason), can you make a separate dataset for testing?

**Comment by reginapramesti** [comment]
@kring I've added some new datasets for testing purposes. The test cases are all in the `wwwroot/test/init/test-dateFormat.json` file.

**Comment by kring** [comment]
Sorry @reginapramesti, this isn't working well for me. I'm visiting http://ci.terria.io/3235-dateformat/#build/TerriaJS/test/init/test-dateFormat.json, and when I try to add pretty much any time-dynamic layer to the map (e.g. `Example Datasets -> Chlorophyll-a concentration (annual)` or `Date format test -> Date-based intervals -> Default date format`), TerriaJS crashes with this exception:

```
DateFormats.js:26 Uncaught TypeError: d.getDate is not a function
    at formatDate (DateFormats.js:26)
    at formatDateTime (DateFormats.js:54)
    at Object.render (DateTimeSelectorSection.js:134)
    at ObserveModelMixin.js:34
    at Function.Uc (knockout-3.4.2.js:52)
    at Function.Vc (knockout-3.4.2.js:51)
    at Function.U (knockout-3.4.2.js:51)
    at Object.a.m.a.B (knockout-3.4.2.js:49)
    at ObserveModelMixin.js:25
    at Object.w (knockout-3.4.2.js:40)
```

It looks like `DateTimeSelectorSection` might be passing an already-formatted date (so, a string) to `formatDateTime`.

**Comment by reginapramesti** [comment]
@kring Fixed the issue, should be all good now. Could you please have a look at it?

**Pull request merged**
