### PR TITLE
Limit workbench item title to 2 lines

### LINKED ISSUE #6341: Improve workbench title padding
http://ci.terria.io/main/#share=s-14QuWsALwB1WNovomZAz2RINYB6

image

If the title is super long, it overlaps onto other items

image

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #6341

Limit the number of lines in workbench item title to 2, and set `min-height` instead of `height` so padding is correct

image

  
### Test me
  
How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

-   ~[ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)~
-   ~[ ] I've updated relevant documentation in `doc/`.~
-   [x] I've updated CHANGES.md with what I changed.
-  ~[ ] I've provided instructions in the PR description on how to test this PR.~

### CODE REVIEW

**Comment by nf-s** [comment]
Thanks for the PR @zoran995 !
I fixed this using a different approach in https://github.com/TerriaJS/terriajs/pull/6357
image

But I think limiting 2 lines might be better. What do you think @philipgrimmett ?

**Comment by nf-s** [comment]
Hi @zoran995 

We think it is best to have the full Workbench item title visible (which is in `main` now from https://github.com/TerriaJS/terriajs/pull/6357) - but think that it would be nice if the title is limited to 2 lines when the item is collapsed

What do you think?

**Comment by zoran995** [comment]
Yeah that is better than always limiting the title, I also added a title attribute which will be useful when the item is collapsed so that the user can get an entire title in a tooltip
image
image

**Review by nf-s — APPROVED** [review]
Thanks @zoran995 !

**Pull request merged**
