### PR TITLE
Update all packages, except the ones we purposely downgraded.

### PR DESCRIPTION
**Pull request by kring**
In response to #1699.  Merging this should close that, too.

### CODE REVIEW

**Comment by kring** [comment]
Ideally, we'd write tests that fail when the two packages kept downgraded, `leaflet` and `superagent`, are upgraded, so greenkeeper can do its thing.  In the Leaflet case, at least, that might be pretty tricky.

**Comment by AlexGilleran** [comment]
Damn Greenkeeper, sign the CLA!

Yeah we might run into more issues with that given that our coverage is pretty low :(

**Comment by kring** [comment]
Yep, but it should at least help us avoid Travis krakens.  We still might find problems when e.g. actually running an app on IE9, but those are generally easier to debug.

**Comment by kring** [comment]
The `superagent` bug was fixed, so that's now upgraded too.  Meaning, the only package from #1699 that this doesn't upgrade is Leaflet.  So this should be ready.

**Pull request merged**
