### PR TITLE
Configurable basemaps from init json

### LINKED ISSUE #907: Allow base maps to be specified in init files
Testing/Playing around with terriajs through a fork of the nationalmap. One observation is that in order to [modify Basemaps](https://github.com/TerriaJS/terriajs/blob/master/lib/ViewModels/createAustraliaBaseMapOptions.js)

I'm pretty sure I'll have to use a modify this in TerriaJS -> and then manually compile TerriaJS instead of installing through npm as another stable dependency. Is there any reason why basemaps couldn't instead be handled as [a json file in the map wrapper under datasources directory](https://github.com/TerriaJS/map/tree/master/datasources) as datasources are currently from template/concatenating and load when the client is accessed [from the "Map" wrapper](https://github.com/TerriaJS/map)? or Can they be currently overwritten if so where/how would this be done

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #907

- Enables defining the list of baseMaps in init files. This was requested a long time ago (#907) but never implemented. When using bingMaps, we check if there is a specified bingMapsKey and, if not, set the default one from `configParameters`.
- Creates a default baseMap list to reflect the existing state
- Implements `previewBaseMapId` init file parameter so dataset preview baseMap can be changed (there is no more a fixed list of available baseMaps so we can't be sure that positron baseMap will exist)

### Testing

Add this to the init file and check that there are only 2 base maps.

```
"baseMaps": [
    {
      "item": {
        "id": "basemap-positron",
        "name": "Positron (Light)",
        "type": "open-street-map",
        "url": "https://basemaps.cartocdn.com/light_all/",
        "attribution": "© <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>, © <a href='https://carto.com/about-carto/'>CARTO</a>",
        "subdomains": ["a", "b", "c", "d"],
        "opacity": 1.0
      },
      "image": "/images/positron.png"        
    },
    {
      "item": {
        "id": "basemap-darkmatter",
        "name": "Dark Matter",
        "type": "open-street-map",
        "url": "https://basemaps.cartocdn.com/dark_all/",
        "attribution": "© <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>, © <a href='https://carto.com/about-carto/'>CARTO</a>",
        "subdomains": ["a", "b", "c", "d"],
        "opacity": 1.0
      },
      "image": "/images/dark-matter.png" 
    }
  ]
}
```

### Pending 

- [x] Check if the base map with a specific id is already added to avoid duplicates
- [x] Tests
- [x] Documentation - *edit all init properties should be documented now*
- [x] Create TerriaMap PR to remove references to deleted functions

### Future work

- Fix share URL so that base map set in it works correctly. @nf-s can we update the parameter for share to `baseMapId` instead of `baseMapName` - _edit I couldn't get share basemap to work on ci next_
- URL parameter `baseMapId` - so user can explicitly set the basemap
- Add attribution traits for all `catalogItems` - _done in #5167_

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by zoran995** [comment]
Thinking right now would it might be better to move the default list to configParameters, or adding the `defaultBaseMaps.json`? Then the user should have an option to specify additional baseMaps in the init file or to remove some using ID. 

*edit* - will move this to future work, after search bar

**Comment by zoran995** [comment]
While writing documentation I also converted all `initData` parameters to table form and added the ones that were missing. Hope everyone is ok with that. From my point of view, this is ready for review.

**Comment by zoran995** [comment]
Docs are still missing the `timeline` and `models` property of `initData`, I wasn't sure if `timeline` is used.
For the `models` I didn't know where it is used, can anyone else document it?

**Review by nf-s — APPROVED** [review]
Thanks for all of your work @zoran995  
Sorry it took so long to review this.

I just made some tiny changes:

- removed references to v7 docs (catalog-items.md, catalog-groups.md...)

- change comment in `DataPreviewMap.jsx`

```
- // Choose positron if it's available
+ // Find preview basemap using `terria.previewBaseMapId`
```

- added breaking changes notice to CHANGES.md

- change default basemap `assetId` to `ionAssetId` for `IonImageryCatalogItemTraits`

**Comment by nf-s** [comment]
I have made issues for the things you noted:

- [Update initialization-files.md documentation](https://github.com/TerriaJS/terriajs/issues/5346)
- [Add `baseMapId` URL parameter ](https://github.com/TerriaJS/terriajs/issues/5347)
- [Share links don't save basemap](https://github.com/TerriaJS/terriajs/issues/5348)

**Pull request merged**
