### PR TITLE
Prevent feature info requests when creating user drawing

### LINKED ISSUE #2949: Mr Mustachio measuring tool waits for unnecessary feature info requests to finish before placing points
When using the Mr Mustachio measuring tool, whenever you click to add a point to the line we are doing feature info requests for all enabled layers, wait for them all to return, and then place the point. This leads to significant lag time in adding points.

As we are not using the feature info when using the measuring tool we should not be sending them in the first place.

### PR DESCRIPTION
**Pull request by mgcsls**
Resolves #2949

### CODE REVIEW

**Comment by soyarsauce** [comment]
💯

**Comment by rowanwins** [comment]
Hi @mgcsls

I gave this a whirl but I'm not sure it's working
http://ci.terria.io/user-drawing-feature-info/#share=s-dxtqSphIAGIwmTGYfdYTutAznSI

- Open the network tab in devtools
- Start using the measure tool and notice that requests are sent, in this case to an endpoint called `identify?f=json`

How were you testing the scenario?

**Comment by mgcsls** [comment]
Hi @rowanwins, thanks for checking the pr! I haven't actually stopped feature info requests from being sent since I thought the main issue was the measuring tool having to wait for feature info requests, rather than the feature info requests themselves. But rereading the issue it seems like I should probably stop the requests altogether while the measuring tool is being used, so I'll try to do that.

**Review by rowanwins — APPROVED** [review]
Looks good @mgcsls !

**Pull request merged**
