### PR TITLE
Bump terriajs-cesium to 1.71 and release new terriajs version

### PR DESCRIPTION
**Pull request by reginapramesti**
### What this PR does

Updates terriajs to use cesium v1.71

### Checklist

-   [X] n/a
-   [X] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by reginapramesti** [comment]
Ignore the branch name, that was a mistake 😬

**Comment by tephenavies** [comment]
This is throwing an error that looks like it's caused by a line missing from a merge:
```
react-dom.development.js:475 Uncaught ReferenceError: cullBackFaces is not defined
    at Globe.push../node_modules/terriajs-cesium/Source/Scene/Globe.js.Globe.pickTriangle (Globe.js:784)
    at MouseCoords.updateCoordinatesFromCesium (MouseCoords.js:77)
    at Object.onMouseMove (TerriaViewerWrapper.jsx:58)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:454)
    at executeDispatch (react-dom.development.js:584)
    at executeDispatchesInOrder (react-dom.development.js:609)
    at executeDispatchesAndRelease (react-dom.development.js:713)
```

**Comment by reginapramesti** [comment]
> This is throwing an error that looks like it's caused by a line missing from a merge:

when does that error come up?

**Comment by tephenavies** [comment]
It came up for me just panning around with 3D Terrain and Bing Maps enabled. Not specifically in any place, I have thousands of the it repeated from almost every frame/tile loaded.

Also there's a couple of requests that look suspect:
```
undefined:1 GET http://ci.terria.io/upgrade-to-cesium-1-69/undefined 404 (Not Found)

Image (async) |   |  
-- | -- | --
  | get | @ | Credit.js:96
  | swapCesiumCredit | @ | CreditDisplay.js:40
  | push../node_modules/terriajs-cesium/Source/Scene/CreditDisplay.js.CreditDisplay.endFrame | @ | CreditDisplay.js:467
  | push../node_modules/terriajs-cesium/Source/Scene/Scene.js.Scene.render | @ | Scene.js:3984
  | push../node_modules/terriajs-cesium/Source/Widgets/CesiumWidget/CesiumWidget.js.CesiumWidget.render | @ | CesiumWidget.js:784
  | render | @ | CesiumWidget.js:44
  | requestAnimationFrame (async) |   |  
  | requestAnimationFramePolyFill | @ | requestAnimationFrame.js:65
  | startRenderLoop | @ | CesiumWidget.js:71
  | set | @ | CesiumWidget.js:560
  | CesiumWidget | @ | CesiumWidget.js:356
  | push../node_modules/terriajs/lib/ViewModels/TerriaViewer.js.TerriaViewer._createCesiumViewer | @ | TerriaViewer.js:383
  | (anonymous) | @ | TerriaViewer.js:614
  | Promise.then (async) |   |  
  | push../node_modules/terriajs/lib/ViewModels/TerriaViewer.js.TerriaViewer.selectCesium | @ | TerriaViewer.js:599
  | push../node_modules/terriajs/lib/ViewModels/TerriaViewer.js.TerriaViewer.selectViewer | @ | TerriaViewer.js:507


```

and 
```
GET http://ci.terria.io/upgrade-to-cesium-1-69/image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIoAAAAcCAYAAAC+uC...ABJRU5ErkJggg== 502 (Bad Gateway)

Image (async) |   |  
-- | -- | --
  | get | @ | Credit.js:96
  | swapCesiumCredit | @ | CreditDisplay.js:40
  | push../node_modules/terriajs-cesium/Source/Scene/CreditDisplay.js.CreditDisplay.endFrame | @ | CreditDisplay.js:467
  | push../node_modules/terriajs-cesium/Source/Scene/Scene.js.Scene.render | @ | Scene.js:3984
  | push../node_modules/terriajs-cesium/Source/Widgets/CesiumWidget/CesiumWidget.js.CesiumWidget.render | @ | CesiumWidget.js:784
  | render | @ | CesiumWidget.js:44
  | requestAnimationFrame (async) |   |  
  | requestAnimationFramePolyFill | @ | requestAnimationFrame.js:65
  | render | @ | CesiumWidget.js:45


```
(I've trimmed out most of that DataURL)

**Comment by tephenavies** [comment]
Both of those come from the Cesium Credit system, I think one is meant to be the Ion logo, which is a broken image
image

**Comment by reginapramesti** [comment]
@steve9164 whenever you have the time, could you have a look at this again please? I've fixed the errors and broken logo 😄

**Review by tephenavies — APPROVED** [review]

**Pull request merged**
