### PR TITLE
wfs search provider + gazetteer search provider

### LINKED ISSUE #4424: Mobx: Gazetteer / Gnaf port
Couldn't find a mobx issue for this.

 steve9164 commented on Mar 18
>We will be porting the remaining 2 search providers.

### PR DESCRIPTION
**Pull request by KeyboardSounds**
### What this PR does

Fixes #4424

This adds a WFS-based Australian Gazetteer search provider to Terria.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by nf-s** [comment]
# Love it!

WFS search provider will be super useful for other things also.

I have a few things to ask:

- Can we cancel old requests if new ones are made before they completed?
- Should we limit requests to at least 2 characters?
- I think we should remove the apology if there are place names - but no locations
image

**Review by nf-s — CHANGES_REQUESTED** [review]
# Love it!

WFS search provider will be super useful for other things also.

I have a few things to ask:

- Can we cancel old requests if new ones are made before they complete?
- Should we limit requests to at least 2 characters?
- I think we should remove the apology if there are place names - but no locations
image

**Comment by KeyboardSounds** [comment]
> * Can we cancel old requests if new ones are made before they complete?

Fixed.

> * Should we limit requests to at least 2 characters?

Fixed.

> * I think we should remove the apology if there are place names - but no locations

Fixed.

**Review by nf-s — APPROVED** [review]

**Comment by nf-s** [comment]
It would be nice to have some sort of warning for searches with less than 2 characters - but that can be left for another day!

**Comment by zoran995** [comment]
@KeyboardSounds we can use this in our app by adding the following lines to `index.js` in TerriaMap. 
```
new AustralianGazetteerSearchProvider({
    terria: terria
})
```
I am creating our own search providers but can't get `zoomTo` working, constantly getting that `currentViewer` is undefined.
From debugger, it seems that terria in the model is defined as `model.terria.terria.currentViewer.zoomTo`. Did you have any similar issue with this?

**Comment by zoran995** [comment]
sorry my bad, I got used to sending objects to the SearchProvider and also typescript

**Pull request merged**
