### PR TITLE
Mobx ui tweaks

### PR DESCRIPTION
**Pull request by soyarsauce**
Small tweaks to map buttons to match styling, bottom half hasn't been implemented due to mobile layout solution not being clear
(Also fixes https://github.com/TerriaJS/terriajs/issues/4026 so you can dev quicker in 2d)

### CODE REVIEW

**Comment by soyarsauce** [comment]
Ready(?!?)

**Comment by KeyboardSounds** [comment]
Related maps looks like this:

image


But otherwise it's very beautiful 😍

**Review by KeyboardSounds — CHANGES_REQUESTED** [review]
Fix the Related Maps and you're good to go!

**Comment by soyarsauce** [comment]
Really annoying... on DT map I let that slide because the login button is to the left of related maps and gave it enough space. I'll see what quick fix we can do

**Comment by rowanwins** [comment]
Also slight issue with button wrapping with map width is less than 575px

screenshot-ci terria io-2020 02 18-15_20_37

**Comment by soyarsauce** [comment]
re; button wrapping:
>(ps vic i need an idea for this:) when the UI is small enough that the buttons run out of room, but not small enough to trigger mobile UI.

>If we are running out of time on the project I dont this this is a huge priority. I mean i am all about making sure this doesnt happen, but in the bigger picture, workbench is still way more important. Especially considering that most people will have their browser quite large.

I will try and whip something up. .

**Comment by soyarsauce** [comment]
Wrapping tweaked like this:
image

**Comment by soyarsauce** [comment]
Wrapping tweaked like this, still happens when you have story and really small width, but it's an improvement.
image

**Comment by soyarsauce** [comment]
& `MenuPanel`s have an option to pass `showDropdownInCenter` as a prop, to do as it describes - open from center instead of offset to the right.
image

**Pull request merged**
