### PR TITLE
fix(package): update json5 to version 1.0.1

### PR DESCRIPTION
**Pull request by kring**
Closes #2905

### CODE REVIEW

**Comment by kring** [comment]
Travis is failing because the latest version of json5 uses [codePointAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt), which is not supported in any version of Internet Explorer.

**Comment by kring** [comment]
https://github.com/json5/json5/issues/170

**Comment by tephenavies** [comment]
It looks like we could update this package to v2 and it should work on IE11

**Comment by kring** [comment]
👍 we're also using/requiring a polyfill library as of TerriaJS v7, so that should help too.

**Pull request merged**
