### PR TITLE
Separate out TableCatalogItem from Csv, SDMX and AbsItt items

### PR DESCRIPTION
**Pull request by RacingTadpole**
This is a small refactor that pulls out the common logic for any catalog item that stores its data as a `TableStructure` into `TableCatalogItem`.
So now `CsvCatalogItem` extends `TableCatalogItem` by providing a `prototype._load` function, and a function to start polling for changed data (`startPolling`).
And `SdmxJsonCatalogItem` and `AbsIttCatalogItem` extend `TableCatalogItem` instead of `CsvCatalogItem`, which just makes a lot more sense, since the former doesn't even read csv data.

It also shifts `setActiveTimeColumn` from `CsvCatalogItem` to `TableStructure.prototype` where it belongs.

This should also prepare the ground for SOS (#1474) and other item types.

You can test it on any csv items, on the ABS ITT items, and on SDMX-JSON at http://localhost:3003/#build/terriajs/test/init/sdmx.json.

### CODE REVIEW

**Comment by kring** [comment]
Mind merging in master?  I tried to do it myself but there are lots of conflicts in `CsvCatalogItem`.

**Comment by RacingTadpole** [comment]
Yes, that was a non-trivial merge. @rdengate - I hope I haven't broken any of the bulk geocoding stuff in there - the tests still pass, but is there a sample geocoding csv file we could add to `csv.init` so I can check manually as well?

**Comment by rdengate** [comment]
> Yes, that was a non-trivial merge. @rdengate - I hope I haven't broken any of the bulk geocoding stuff in there - the tests still pass, but is there a sample geocoding csv file we could add to csv.init so I can check manually as well?

I don't know what csv.init is, but there are test csvs in the Terria test/csv dir, such as 100addresses.csv and address_to_lat_long.csv. However, none of the Terria maps have the batch geocoder enabled, which means that to test you need to add it into the index file like so:
`var GnafAddressGeocoder = require('terriajs/lib/Map/GnafAddressGeocoder.js');
terriaOptions.batchGeocoder = new GnafAddressGeocoder();
`

**Comment by RacingTadpole** [comment]
@rdengate - very cool! I just tried it out - looks awesome!
@kring - this is ready for another look now.

**Comment by rdengate** [comment]
@RacingTadpole thanks :-D

**Pull request merged**
