### PR TITLE
Improve magda root group behaviour for sharing

### PR DESCRIPTION
**Pull request by soyarsauce**
### What this PR does

Fixes https://github.com/TerriaJS/qld-digital-twin/issues/237 & https://github.com/TerriaJS/terriajs/issues/4978

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by nf-s** [comment]
I'm not that happy with this solution, it is applying a quick fix to a quick fix which led to a bug. 

I'd much rather just reverting the change for maps this issue affects - eg just commenting/uncommenting lines for qld/nsw digital twin terriaJS:

https://github.com/TerriaJS/terriajs/blob/69f045dc5f82efb3c91c2a8193a240f968177834/lib/Models/Terria.ts#L920-L923

I believe those maps are already using custom terriaJS versions

**Comment by soyarsauce** [comment]
Hey @nf-s - thanks for taking a look! And I agree it's definitely not ideal at all. However it _is inline_ and a halfway measure to achieving the 'share key'/'alias id' concept in https://github.com/terriajs/terriajs/issues/4774.

Re: QLD/NSW - they've historically used official (alpha) terriajs releases, only recently has QLD diverted slightly for the WIP outlines work. NSW is still using official. SaaS as well.

The problem with reverting it for SaaS however, means we then break sharing in a different way by unfixing what the original quick fix addressed. Do you have any other ideas on how we can move forward without share keys being finalised?

**Comment by nf-s** [comment]
Would we need to revert this change for SaaS? I thought it was working well in SaaS.
In my mind, this revert would only need to happen for QLD (and NSW when the next release occurs - if they upgrade terriajs to the problem version).

I would much prefer a rough `shareKeys` implementation than a fix like this if possible.   
If we had that we could just add `shareKeys = ['/']` for the root magda group.

What do you think?  
I don't have a good idea of how urgent this is right now, so I you think we need this fix now I'm happy to approve it.

**Comment by soyarsauce** [comment]
SaaS has the same problem as QLD(and NSW should it update), in that some of those saasmaps that are magda based (QLD+NSW are "fully magda based maps"). So any share links created before the change, are no longer working at the moment - I've slated today for architecture documentation and was hoping for someone to be able to look after this in the meantime.

None of the current prod saas maps that are magda based are actually in "production" yet, the only production saas maps are utilising other means of catalogue-ing - DE africa is the one magda-based catalog that comes to mind, which is the only reason why I am ok with taking a slower approach for it, but IMO QLD definitely needs action (in the form of a roll back, or a fix like this).

**Review by nf-s — APPROVED** [review]

**Pull request merged**
