### PR TITLE
Add CameraView.lookAt and CameraView.fromPositionHeadingPitchRoll

### PR DESCRIPTION
**Pull request by kring**
These functions were requested by a user bringing a Google Earth application over to TerriaJS, and provide a more flexible way to position the camera.

### CODE REVIEW

**Comment by stevage** [comment]
Don't think I can meaningfully review this - 3D maths is over my head.  From your description it sounds like these functions will be called directly by things outside TerriaJS itself? 

Would it be worth exposing this as an option for init files in Terria.addInitSource? Something like:

```
    if (defined(initSource.initialTarget)) {
        this.homeView = CameraView.fromLookAt(...)
    }
```

Also, test cases? :)

**Comment by kring** [comment]
Haha ok thanks for calling me on the lack of tests.  I'll add some soon.

Yeah it could be worth rolling into the initialView and homeView properties in the init file.  That's a good idea.  Currently it's mostly just there for user/app code that needs it.  Specifically, an app that is moving from Google Earth to TerriaJS in this case.

**Comment by kring** [comment]
@stevage this is ready for another look.

**Comment by kring** [comment]
@stevage please review and merge this when you get a moment.

**Comment by RacingTadpole** [comment]
Hey guys, I'm hoping to review a few PRs this morning - do you want me to look at this one too @stevage?

**Comment by stevage** [comment]
Yes please @RacingTadpole - sorry it's not this morning anymore

**Comment by kring** [comment]
@RacingTadpole do you think you might get to this one before our NM release tomorrow?  It's not strictly needed for the release, but it's been hanging around awhile and should be pretty low impact.

**Comment by RacingTadpole** [comment]
Sure, it had fallen off my radar - I'll take a look asap.

**Comment by RacingTadpole** [comment]
This is probably somethings stupid I'm doing, but I can't get the tests to run without crashing with this error: `Uncaught Error: Cannot find module '../CustomMatchers'`. I can't work out why that's happening - the file is certainly there, and I've restarted `gulp` and `npm start` for good measure. Any ideas?

**Comment by stevage** [comment]
Have you `rm -rf node_modules && npm install` in both NM and TerriaJS too? :)

**Pull request merged**
