### PR TITLE
Share featureinfo panel

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

Fixes https://github.com/TerriaJS/terriajs/issues/4837

Ports the code for sharing feature info panel from `master`

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by rowanwins** [comment]
The only thing I've noticed @na9da is that the feature info doesn't close when you move to the next scene in a story which was something Robbi had brought up somewhere 
eg http://ci.terria.io/share-featureinfo/#share=s-dp9RAOsBAPlomnYp9GMxHl9cVfd

**Review by rowanwins — APPROVED** [review]
Looks good other than my minor comment which was semi-related to this issue.

**Comment by na9da** [comment]
> The only thing I've noticed @na9da is that the feature info doesn't close when you move to the next scene in a story which was something Robbi had brought up somewhere
> eg http://ci.terria.io/share-featureinfo/#share=s-dp9RAOsBAPlomnYp9GMxHl9cVfd

Yeah, I have noticed the same in `master`. I'll see how I can fix it :+1:

**Review by rowanwins — APPROVED** [review]
Looks good to me!

**Pull request merged**
