### PR TITLE
Asynchronous HTTP 202 + user cancellation

### PR DESCRIPTION
**Pull request by Jason-DNetto**
Instantiating the cesium Request object in TerriaJsonCatalogItem and passing it down through to cesium Resource objects, so that the user clicking 'Remove' on the ResultPendingCatalogItem cancels the Request in the request object and stops creating xhr calls.

made against the cesium-1.46 branch as requested in https://github.com/TerriaJS/terriajs/pull/3037

### CODE REVIEW

**Comment by Jason-DNetto** [comment]
Is there going to be any more feedback for this pull request?

Thanks
Jason

Jason D’Netto | e-Research Analyst/Research Support Specialist | eResearch | Queensland University of Technology (QUT) | 2 George St, GPO Box 2434, Brisbane 4001 AUSTRALIA | CRICOS 00213J | Phone : 3138 4478 |  Email : j.dnetto@qut.edu.au<mailto:j.dnetto@qut.edu.au>

**Comment by kring** [comment]
Yes! Sorry for the delay.

**Comment by kring** [comment]
Apparently GitHub closed this when I deleted the `cesium-1.46` branch (to replace it with a `cesium-1.48` branch). Mind re-opening it against cesium-1.48?

**Comment by kring** [comment]
Actually, #3037 is fine, no need to open another PR.

**Pull request closed without merging**
