### PR TITLE
Handle WMS time interval specification

### LINKED ISSUE #942: Handle WMS time inverval specification
In our WMS services serving model results, which tend to have unifom time spacing, we can save a lot of space in the `getCaps` by using the WMS time interval specification like this instead of specifying the complete list of time values explicitly

```
<Extent name="time">
2013-12-05T01:00:00/2014-09-29T12:00:00/PT1H,2014-10-07T01:00:00/2015-09-24T12:00:00/PT1H
</Extent>
```

Here's a full example `getCaps`: 
http://tampabaymap.org/sci-wms/wms/datasets/wfsfvcomagg?service=WMS&version=1.3.0&request=GetCapabilities

But it seems that the TerriaJS code cannot handle this, expecting a simple list of times instead:
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js#L527-L541

It would be great to handle the WMS  time interval specificatiion in TerriaJS so that problems like this could be solved: https://github.com/sci-wms/sci-wms/issues/80#issuecomment-144071139

### PR DESCRIPTION
**Pull request by RacingTadpole**
Fixes #942
I have tested it on the endpoint http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities - the "sea_water_potential_temperature" layer in particular shows time variation.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
FWIW, @metanomy tested this PR and showed me it was working:
image

**Comment by metanomy** [comment]
@RacingTadpole Make sure to claim your bounty: https://www.bountysource.com/issues/27033178-handle-wms-time-inverval-specification

**Comment by rsignell-usgs** [comment]
Hurrah for @RacingTadpole :horse_racing: :frog:

**Comment by RacingTadpole** [comment]
yay! :-)

**Comment by RacingTadpole** [comment]
BTW, I work at NICTA, so I'll share this with the team.

**Comment by metanomy** [comment]
@RacingTadpole Share the code or the bounty? ;)

**Comment by RacingTadpole** [comment]
The bounty - and thank you for offering it!

**Comment by kwilcox** [comment]
:+1: thanks @RacingTadpole

**Pull request merged**
