### PR TITLE
Fix compass help bug

### LINKED ISSUE #4673: Mobx: compass points to non-existent default navigation help
The compass will tempt you to `Find out more about the controls and how to use them.` , only to open out to a dead help panel (as well as the `help` button that comes out of the compass)

This was supposed to be filled out by https://github.com/TerriaJS/terriajs/issues/4189 but that's been backlogged now

We should improve the defaults

image

### PR DESCRIPTION
**Pull request by reginapramesti**
### What this PR does

Fixes #4673 and implements #4582

Implemented new compass design, which in turn fixes the compass help button bug. Also enabled users to permanently disable compass controls from the dropdown. 

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by zoran995** [comment]
also fixes #4409

**Comment by reginapramesti** [comment]
There's still the bug described https://github.com/TerriaJS/terriajs/issues/4177. I tried to fix it but after some investigation, I think it's a bigger problem than it looks. Tried adding the `onDismissed` props in `CleanDropdownPanel` but it behaves strangely, which, after some more investigation, I found is because `CleanDropdownPanel` never calls `this.open()`, unlike the generic `DropdownPanel` class. That function does some trickery to work with the `onDismissed` props. 

Anyway I think I'll leave this bug for now and will focus on other more important bugs

**Comment by KeyboardSounds** [comment]
This looks great! The only thing I'm wondering about is whether the little arrow dropdown icon should be replaced by a ❓ icon instead. Otherwise it looks like a settings menu.

**Comment by reginapramesti** [comment]
Yeah that's a good idea, I was initially just following the designs but then Wing suggested for the dropdown to be below the button rather than to the left (for various reasons) and so we just changed it from a left arrow to a down arrow 😂

**Review by KeyboardSounds — APPROVED** [review]

**Pull request merged**
