### PR TITLE
Fix Timeline that doesn’t restart after it has been closed once

### LINKED ISSUE #7163: Timeline Play broken after Timeline closed once
After closing the timeline once (with the appropriate button "Use timeline"), if you reopen it, the "Play" button of the timeline no longer starts the flow of time.

image

### PR DESCRIPTION
**Pull request by glughi**
### What this PR does

Fixes #7163 

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Review by na9da — APPROVED** [review]
Hi @glughi - good catch.

Thanks for the PR, merging in.

**Review by na9da — APPROVED** [review]

**Review by na9da — CHANGES_REQUESTED** [review]
I guess there is a merge issue with CHANGES.md file which prevents this PR from getting merged.. Could you please sync your branch with the latest main? Thanks!

**Comment by glughi** [comment]
Done.

**Review by na9da — APPROVED** [review]

**Comment by na9da** [comment]
Thanks @glughi. 

Merging :rocket:

**Pull request merged**
