### PR TITLE
Update compass width

### PR DESCRIPTION
**Pull request by soyarsauce**
### What this PR does

Fixes https://github.com/TerriaJS/terriajs/issues/4261 by making the base scaling from 56px
Currently it's 55px.
56px looks better

image

### Checklist

-   [x] unit test not applicable
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by soyarsauce** [comment]
11:41
Default load looks good
Screenshot 2020-04-30 11.41.18.png 
Screenshot 2020-04-30 11.41.18.png

11:42
Rollover makes the outer ring shift to the right
Screenshot 2020-04-30 11.39.12.png 

btw @soyarsauce i did also notice that the middle button here has rounded corners (edited)

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/terriajs/issues/4261#issuecomment-621672515

**Review by na9da — APPROVED** [review]
Looks good to me!

:+1:  for the detailed explanation.

**Comment by tephenavies** [comment]
@soyarsauce Needs conflicts to be resolved.

**Pull request merged**
