### PR TITLE
Beautiful fonts

### PR DESCRIPTION
**Pull request by soyarsauce**
Make fonts match Phil's sketchs on MacOS

### CODE REVIEW

**Comment by soyarsauce** [comment]
DO NOT MERGE YET! requires further discussion

**Comment by soyarsauce** [comment]
>I’m going to leave that for next month. It’s a change that will require discussion and reworking some things

**Comment by soyarsauce** [comment]
(Some other stuff I forgot to add here)
we haven't added it yet or will probably never, so we need to decide how we marry the designs vs web implementation

https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
https://www.zachleat.com/web/font-smooth/
https://github.com/google/fonts/issues/1170

**Comment by soyarsauce** [comment]
Re: https://github.com/TerriaJS/nsw-digital-twin/issues/244#issuecomment-599874120 bringing it up again

**Comment by Myndex** [comment]
Hi @soyarsauce 

This thread was linked to a related one, so to chime in on the topic:

There are several reasons that "-webkit-font-smoothing: antialiased;" and other font smoothing properties **do _NOT_ show fonts off at their best**. What does show fonts at their best is the _DEFAULT_ for the given device, and this is nearly always subpixel antialiasing. The font-smoothing "antialiasing" property is inferior to the default subpixel antialiasing both in quality and by reducing contrast needlessly — in fact the contrast reduction alone can make a font unreadable in some cases.

IMO, _font-smooth_ is a CSS property that should be depreciated. Best results are to use the device's default antialias which is optimized for that device. That provides the best and most consistent results.

See also:  http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

Thank you,

Andrew Somers
_Myndex Color Science Researcher
W3C WAI/WCAG Invited Expert_

**Pull request closed without merging**
