### PR TITLE
Mobx: CompositeCatalogItem

### PR DESCRIPTION
**Pull request by mgcsls**

### CODE REVIEW

**Comment by soyarsauce** [comment]
Restarted CI job

**Comment by rowanwins** [comment]
Can you provide an example config @mgcsls ?

**Comment by mgcsls** [comment]
This pr is mostly just for TerriaJS/nsw-digital-twin#326, but if you wanted an actual catalogue item I guess you could do something like
```
{
  "name": "geology and bike",
  "type": "composite",
  "members": [
     {
       "url": "http://services.ga.gov.au/gis/rest/services/GA_Surface_Geology/MapServer",
       "type": "esri-mapServer",
       "name": "Surface Geology"
     },
     {
       "type": "geojson",
       "name": "GeoJSON Test",
       "url": "test/bike_racks.geojson"
      }
   ]
 }
```

Note this is a very basic `CompositeCatalogItem` so it doesn't combine things like the members' descriptions or legends or anything like that, just the map items.

**Comment by na9da** [comment]
Merged in mobx branch to fix the CI heap issue.

**Comment by rowanwins** [comment]
Just added the `isMappable` property  so the chart icon doesn't show on the workbench item.

**Review by rowanwins — APPROVED** [review]
Looks good and works

**Pull request merged**
