### PR TITLE
New user interface 

### PR DESCRIPTION
**Pull request by chloeleichen**
:sweet_potato: 
:sweet_potato: 

Nice things Kevin said in another PR: 

> This was a huge effort! Just look at the statistics! 1718 commits! 557 files changed! 12 contributors! Congratulations everyone!
> 
> The old UI has been branched to oldui. Even though it's not quite perfect yet, the new UI already much better than the old UI in virtually every way. Does anyone have a reason we shouldn't merge the new UI into master?

And 

:sweet_potato:

### CODE REVIEW

**Comment by AlexGilleran** [comment]
:-1: not fit for purpose. We should start again from scratch :)

**Comment by kring** [comment]
> We should start again from scratch :)

C++ and emscripten this time maybe?

**Comment by AlexGilleran** [comment]
> C++ and emscripten this time maybe?

The future is Adobe Flash

**Comment by kring** [comment]
:shipit:

**Pull request merged**
