### PR TITLE
Change "Raster Map Quality" to be just "Map Quality".

### LINKED ISSUE #6394: one word fix: rename "Raster Map Quality" to "Map Quality"
The "Raster Map Quality" slider actually affects other things apart from raster maps - also affects 3D visual quality and probably other things. Therefore we should rename it to "Map Quality".

Screen Shot 2022-07-06 at 12 22 11

### PR DESCRIPTION
**Pull request by meh9**
Fixes #6394

### What this PR does

Fixes #6394

The "Raster Map Quality" slider actually affects other things apart from raster maps - also affects 3D visual quality and probably other things. Therefore I have renamed it "Map Quality".

### Test me

Open the CI build and click Map Settings, the bottom slider should now be named "Map Quality".

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by meh9** [comment]
@staffordsmith83 want to review this? :)

**Comment by staffordsmith83** [comment]
> @staffordsmith83 want to review this? :)

Sure thing! Looks good I will just test first to be sure

**Review by staffordsmith83 — APPROVED** [review]
Looks good! But I think we should make another ticket to flag the translations as requiring update too: e.g. When switching to French I see the name is still "Qualité de la carte raster"

**Comment by staffordsmith83** [comment]
I have posted a question here for the best workflow: https://github.com/WeblateOrg/weblate/discussions/8870
but I think its going to be this button, once our updated source string is pushed to Weblate:
Screen Shot 2023-03-02 at 7 36 11 am

**Pull request merged**
