### PR TITLE
Tiff imagery provider support

### PR DESCRIPTION
**Pull request by staffordsmith83**
### What this PR does

Fixes [#156](https://github.com/TerriaJS/product/issues/156)

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Test me

This should open the branch with a catalog of COGs to test:
http://ci.terria.io/tiff-imagery-provider-support/#clean&https://gist.githubusercontent.com/staffordsmith83/ed48ca27d1c4c8d36d130ce6a8098fd7/raw/16206b8e9e114af8e02f5e5082cf935fd3e1281c/example_cogs_catalog.json

Try the example COGs provided in 2D and 3D mode.

### Checklist

~~
- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.
~~

### CODE REVIEW

**Comment by AnaBelgun** [comment]
Meeting with Kevin and Stephen to decide next steps on using one library for 2D and 3D

**Comment by zoran995** [comment]
Hi, I wonder if it is plan to merge this into a main or have it as a officially supported terriajs plugin?
I would vote second option as it add an extra dependencies and bundle size and not everyone will need the cog support. Also it could give community certainty in plugin support and that it will be supported in long term. But would also like to hear team opinion on this 😃

**Comment by staffordsmith83** [comment]
> Hi, I wonder if it is plan to merge this into a main or have it as a officially supported terriajs plugin? I would vote second option as it add an extra dependencies and bundle size and not everyone will need the cog support. Also it could give community certainty in plugin support and that it will be supported in long term. But would also like to hear team opinion on this 😃

Good idea @zoran995 we will discuss today. I can also calculate a bundle size increase to see how bad it would be, thanks for your suggestion.

**Comment by staffordsmith83** [comment]
UPDATE 19 July 2023: 
This will be a draft for some time.
TODO: Assess bundle size bloat, ask @na9da if possible to implement as a plugin instead.

**Comment by staffordsmith83** [comment]
> Hi, I wonder if it is plan to merge this into a main or have it as a officially supported terriajs plugin? I would vote second option as it add an extra dependencies and bundle size and not everyone will need the cog support. Also it could give community certainty in plugin support and that it will be supported in long term. But would also like to hear team opinion on this 😃

Dear @zoran995 we will implement this using lazy loading to not bloat the bundle size, but the rest of the team would like to have it in core.

**Comment by staffordsmith83** [comment]
Replacing this branch with a better named `cloud-optimised-geotiff-main` - Did not rename, as would like to preserve this branch in CI to preserve all existing test links in tickets.

**Pull request closed without merging**
