### PR TITLE
Fix HelpMenuPanel open state props

### PR DESCRIPTION
**Pull request by soyarsauce**

### CODE REVIEW

**Comment by chloeleichen** [comment]
@soyarsauce I don't see `HelpMenuPanel` being used anywhere, is there a specific instance that i should look at?

**Comment by soyarsauce** [comment]
@chloeleichen https://github.com/TerriaJS/soe/blob/9b900f9d4102ea2ef38b793db4214f8f9247531e/lib/Views/UserInterface.jsx 👍

**Comment by kring** [comment]
@soyarsauce this is to fix the SoE help menus not working, right? It would be good to mention that in the issue description. Can we even say it fixes #3362?

**Comment by soyarsauce** [comment]
Yes, this alone would actually address the "bring back to life" aspect of #3362 but the other parts need a bit more defining, separately https://github.com/TerriaJS/soe/pull/7 should fix SoE help

**Review by chloeleichen — APPROVED** [review]
Thanks @soyarsauce

**Pull request merged**
