### PR TITLE
Add basic CSW support

### LINKED ISSUE #777: Add CSW support
We have a requirement for handling CSW catalog services in AREMI.

A live CSW 2.0.2 server is available here:

http://www.marlin.csiro.au/geonetwork/srv/eng/csw?&request=GetCapabilities&service=CSW&version=2.0.2

To run a local service we can use this:

http://sourceforge.net/projects/geonetwork/files/GeoNetwork_opensource/v2.10.4/

### PR DESCRIPTION
**Pull request by kring**
Added `CswCatalogGroup`.  By default, it queries for records where the `dc:format` or `apiso:ServiceType` property starts with `OGC:WMS` and then looks for `dc:URI` XML elements with a `protocol` attribute of `OGC:WMS`.  This works with the marlin CSW server in #777, but may not be suitable for other CSW servers.

We can perform a different query by specifying the XML query in the `getRecordsTemplate` property of `CswCatalogGroup`.  The text to look for in the `protocol` attribute can be specified as well, using a regular expression.  And other formats can be used in much the same way as `CkanCatalogGroup` (e.g. `includeGeoJson: true`.

We'll likely need to extend this as we try to access more CSW servers, but it's a good start, and probably about the best we're going to do in the absence of some additional real-world examples to test with.

Fixes #777

### CODE REVIEW

**Comment by kgrochow** [comment]
With the NM postProxy branch and this branch, I'm getting CORS issues with all the example servers except for for oa-gis.csiro.au and marlin.csiro.au.  Is that to be expected?

**Comment by kring** [comment]
Yeah, I didn't add them to the proxy list because I'm assuming we don't want NM to be able to proxy those servers.  You can add them manually for testing.  None of those servers actually have any results, though, for the reasons discussed in #777.

**Comment by kgrochow** [comment]
I've been loosely following the #777 conversation, but not very closely.  I guess having them in our test list isn't a problem while we see if we can come up with a better resolution.  We might want to remove them down the road if we determine we can't/won't support them indefinitely.

**Comment by rsignell-usgs** [comment]
I've been investigating this a bit more, and it seems that the CSW services by geoportal servers allow query for WMS (and other service) endpoints via `apiso:ServiceType`, but instead of using the suggested [link types recommended here](https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv), they are still using `urn:x-esri:specification:ServiceType:wms:url` for WMS.   See cells [16] and [17] in this notebook:
http://nbviewer.ipython.org/gist/rsignell-usgs/95f3928787710454135f

So if we just changed this line:
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CswGetRecordsTemplate.xml#L14
from 
`<ogc:Literal>OGC:WMS*</ogc:Literal>`
to 
`<ogc:Literal>*WMS*</ogc:Literal>`
then we should get 981  layers back from the geoportal CSW endpoint at `http://www.ngdc.noaa.gov/geoportal/csw`

**Comment by kring** [comment]
@rsignell-usgs  I've made some changes in the `cswReferences` branch that make the NGDC server work (you'll need to make sure config.json is set to allow that server to be proxied).  In addition to what you mentioned above, I also had to change how TerriaJS finds the WMS resources in the CSW record.  The marlin server includes XML elements like this:

``` xml
<dc:URI protocol="OGC:WMS" name="mnf:CTD_HEADER_AODN_VIEW" description="CTD data for Southern Surveyor Voyage SS2013_T03">http://www.cmar.csiro.au/geoserver/wms?&amp;CQL_FILTER=SURVEY_NAME%20%3D%20%27SS2013_T03%27</dc:URI>
```

But the NGDC server doesn't include `URI` elements at all.  Instead, the WMS URL is found in an element like this:

``` xml
<dct:references scheme="urn:x-esri:specification:ServiceType:wms:url">http://thredds.coastal.ufl.edu:8080/thredds/wms/CH3D-SSMS/EastCoast/2D/NAM-FC/EASTCOAST-2D-NAM_fmrc.ncd?service=WMS&amp;version=1.3.0&amp;request=GetCapabilities</dct:references>
```

So I've taught TerriaJS to work with this sort of thing, too.  Since there's no obvious layer name in the `dct:references` element, I'm assuming that the record is intended to refer to the entire WMS server.

So this works, but I don't completely understand why these two CSW servers have such drastically different ways of representing a WMS resource.

**Comment by rsignell-usgs** [comment]
@kring Fantastic!  We need to work on harmonization with CSW service providers, but this will get us going for testing TerriaJS with IOOS (Integrated Ocean Observing System) services.  Bringing in the technical  IOOS folk here @dpsnowden, @lukecampbell

**Comment by rsignell-usgs** [comment]
@kring, I'm finally up for air and testing this out.   I think I have the `terriaJS` `cswReferences` branch installed correctly, but I'm not sure what an example CSW json file `./map/wwwroot/init/csw.json` file should look like.    

Do you have an example?

**Comment by kring** [comment]
Yes there's an example in the branch:
https://github.com/TerriaJS/terriajs/blob/cswReferences/wwwroot/test/init/csw.json

**Comment by rsignell-usgs** [comment]
@kring, sheesh I had searched the repo for "csw.json" instead of "csw"!   :scream_cat:

**Comment by rsignell-usgs** [comment]
@kring, okay, I added the csw.json and added the csw endpoints to the proxy list and did `npm restart` and now the CSW endpoints show up on http://comt.sura.org/proxy_3001, but if I select `NGDC Geoportal`, I get "This group does not contain any items".    How can I debug my setup?

**Comment by rsignell-usgs** [comment]
@metanomy, by chance have you got the CSW stuff working on your end?

**Comment by metanomy** [comment]
@rsignell-usgs I haven't tried CSW yet. Are you using Docker for your terriaJS images? If so, send me your Dockerfile and I'll try to replicate on my end.

As for troubleshooting, the container log (e.g., "docker logs <container_name>") helps a lot to figure out where there are errors. The Javascript console also gives me insight sometimes.

**Comment by kring** [comment]
@rsignell-usgs did you add the server to the proxy whitelist in config.json?  If that's not it, I'll try to check it out tonight.  Sorry for the slowness, I'm with my family in the US for the next few weeks.

**Comment by kring** [comment]
@rsignell-usgs sorry I just re-read your message and saw that you had already added the servers to the proxy whitelist.  So I checked it out and the problem is that the CSW requires that POST requests be proxyable.  I added the capability to `server.js` in NationalMap, but hadn't integrated it over the TerriaJS/map yet.  So I've now done in that in the `usgs` branch and that NGDC Geoportal should work out of the box when you visit this URL:
http://localhost:3001/#build/TerriaJS/test/init/csw.json

**Comment by rsignell-usgs** [comment]
@kring, I pulled down your changes to the `map` repo, switched to the `usgs` branch, added my servers to the white list, added  https://github.com/TerriaJS/terriajs/blob/cswReferences/wwwroot/test/init/csw.json as `wwwroot/init/csw.json` and set 

```
    "initializationUrls" : [
        "csw"
    ],
```

in `config.json`.

When I try out the server at http://comt.sura.org/proxy_3001/, I get "unsupported catalog item type: csw", see attached screen grab:
8-20-2015 4-35-04 pm

Is there some other setting I forgot to set?

**Comment by kring** [comment]
@rsignell-usgs maybe missing an `npm install`?  The `usgs` branch is configured to install the `cswReferences` branch of TerriaJS.  If everything is configured properly the localhost URL above should work; no need to copy `csw.json` anywhere.

**Comment by rsignell-usgs** [comment]
I don't know what I did wrong before, but doing

```
 git clone https://github.com/TerriaJS/map.git
 cd map
 git checkout usgs
 npm install
 ./node_modules/gulp/bin/gulp.js
 npm start
```

and then pointing my browser at http://comt.sura.org/proxy_3001/#build/TerriaJS/test/init/csw.json worked just fine!

Only the NGDC CSW seems to work.  The data.gov CSW doesn't find any items, and the NODC CSW and CIDA CSW both report that the getrecords request failed.   And while most of the WMS endpoints obtained from the CSW search at NGDC don't have CORS enabled, a few of them do! @scross015, you are one of the few!  Here's proof:
8-22-2015 6-49-40 am

@kring, thanks for sticking with me on this!

**Comment by rsignell-usgs** [comment]
@dpsnowden, so yes, TerriaJW can query CSW endpoints like the NGDC Geoportal now.   To make this an effective viewer for the WMS services from THREDDS and Sci-WMS we would still need to add to TerriaJS the ability to select vertical layer and specify the color range.

**Comment by metanomy** [comment]
@rsignell-usgs @dpsnowden - congrats on FVCOM data in TerriaJS!

For color range inspiration, take a look at the ewatercycle demo app (http://forecast.ewatercycle.org/, source here: https://github.com/NLeSC/eWaterCycle-Demo).  We might be able to repurpose their layer picker as a vertical layer selector, although it seems more functional than elegant. 

And since we're talking time series data over vertical layers, I just have to mention a crazy idea: NOAA's Weather and Climate Toolkit (http://www.ncdc.noaa.gov/wct/formats.php) supports generating KML/COLLADA files of multi-layer radar sweeps. Wouldn't it be clever if we could repurpose the same code (adding in the required gltf step), to place a 3D animation of multi-layer FVCOM data? 

There are several immediate challenges to usability (removing the ocean "skin" in Cesium, adding in a bathymetry layer, selecting a useful transparency scheme). But I think it's all doable with a little bit of integration elbow grease.

**Comment by kring** [comment]
> Only the NGDC CSW seems to work.

Yes, that's right.  Well, marlin.csiro.au works too, but it's very slow.  The others are there for testing but don't currently return any results for various reasons.  I had previously documented the reasons here (though it may be out of date by now, I haven't checked):
https://github.com/TerriaJS/terriajs/issues/777

**Comment by rsignell-usgs** [comment]
We now have NODC CSW working, thanks to @Yuanjie0913 enabling `apiso:ServiceType` queries on the provider side:
8-24-2015 5-17-14 pm

**Comment by rsignell-usgs** [comment]
@kring, I was hoping to show this at the ESIP meeting here in DC on Friday, but http://comt.sura.org/proxy_3001/#build/TerriaJS/test/init/csw.json
is no longer working for me, so I imagine the problem is I'm no longer using a version of TerriaJS that does not support this.  

Is this CSW capability only in the USGS branch?

**Comment by kring** [comment]
Yeah I think you may need to use a custom branch of Terria.  Can you remind me which server in that csw.json was working before, and I'll check it out?  marlin.csiro.au is still working, for what it's worth.

**Comment by rsignell-usgs** [comment]
Yes, I saw that `marlin.csiro.au` was working, but `ngdc` and `nodc` were working before (both "geoportal servers") and now they are not.  

 I would really like it if `geoport.whoi.edu` was working, as that is a "pycsw" server...

**Comment by rsignell-usgs** [comment]
Here's an ipython notebook that explores these 3 csw endpoints:
http://nbviewer.ipython.org/gist/rsignell-usgs/efff0a16e29da78a4f8f

**Comment by kring** [comment]
I just sync'd the `cswReferences` branch of TerriaJS with master.  If you switch your fork of NM to use that, the NGDC Geoportal group should work again.  I'll try to PR this into master today.

"NODC Geoportal" still returns no records for the query we're doing.  And USGS Woods Hole GI_CAT (geoport.whoi.edu) took several minutes and then finally returned 502 (Proxy Error).

If you want to try tweaking the query we make to the CSW server, it's in `CswGetRecordsTemplate.xml`.

**Comment by rsignell-usgs** [comment]
Crud.  I still can't reproduce our success from a few months ago here:
https://github.com/TerriaJS/terriajs/pull/860#issuecomment-134384183

I modified `package.json`:

```
...
    "supervisor": "^0.6.0",
    "terriajs": "git://github.com/TerriaJS/terriajs#cswReferences",
    "terriajs-cesium": "1.13.0",
```

did

```
npm install 
npm restart
```

but still getting no layers from any CSW servers except marlin when I try:
http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/csw.json

It seems the `getRecords` requests are okay, so perhaps the problem is in how TerriaJS is trying to determine the WMS endpoints from the returned records?

Where does that logic happen?

**Comment by rsignell-usgs** [comment]
If we were to get one CSW endpoint going for the demo tomorrow,  it would be this one:

```
http://geoport.whoi.edu/csw
```

since it uses pycsw (the same as data.gov) but is up-to-date with the agreed upon way to represent WMS endpoints in the returned records ("OGC:WMS").

This notebook shows the CSW endpoint, the getRecords request for datasets with WMS endpoints, and the way the WMS endpoints are returned in the "references"

http://nbviewer.ipython.org/gist/rsignell-usgs/0fc4f5cd1f85ec411458

As you can see, the request is:

```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ogc="http://www.opengis.net/ogc" outputSchema="http://www.opengis.net/cat/csw/2.0.2" outputFormat="application/xml" version="2.0.2" service="CSW" resultType="results" maxRecords="100" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName><csw:Constraint version="1.1.0"><ogc:Filter><ogc:PropertyIsLike wildCard="*" singleChar="?" escapeChar="\\"><ogc:PropertyName>apiso:AnyText</ogc:PropertyName><ogc:Literal>*CMG_Portal*</ogc:Literal></ogc:PropertyIsLike></ogc:Filter></csw:Constraint></csw:Query></csw:GetRecords>
```

and I think indeed this is what TerriaJS is requesting.

The WMS endpoint is contained in returned records like this one:

```
<csw:SummaryRecord xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inspire_common="http://inspire.ec.europa.eu/schemas/common/1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dct="http://purl.org/dc/terms/" xmlns:ows="http://www.opengis.net/ows" xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:ogc="http://www.opengis.net/ogc" xmlns:fgdc="http://www.opengis.net/cat/csw/csdgm" xmlns:inspire_ds="http://inspire.ec.europa.eu/schemas/inspire_ds/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:os="http://a9.com/-/spec/opensearch/1.1/" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"><dc:identifier>gov.usgs.cmgp:COAWST.Barnegat_Bay.spring2012</dc:identifier><dc:title>COAWST Hindcast:Barnegat Bay:ADCIRC tides,Real rivers,Plume,Lowpass Espresso bdry,NAM,new bathy</dc:title><dc:type>dataset</dc:type><dc:subject>CMG_Portal</dc:subject><dc:subject>sea_floor_depth</dc:subject><dc:subject>water_surface_height_above_reference_datum</dc:subject><dc:subject>barotropic_x_sea_water_velocity</dc:subject><dc:subject>barotropic_y_sea_water_velocity</dc:subject><dc:subject>sea_water_potential_temperature</dc:subject><dc:subject>sea_water_salinity</dc:subject><dc:subject>ocean_s_coordinate_g1</dc:subject><dc:subject>ocean_s_coordinate_g1</dc:subject><dc:subject>longitude</dc:subject><dc:subject>latitude</dc:subject><dc:subject>longitude</dc:subject><dc:subject>latitude</dc:subject><dc:subject>longitude</dc:subject><dc:subject>latitude</dc:subject><dc:subject>longitude</dc:subject><dc:subject>latitude</dc:subject><dc:subject>time</dc:subject><dct:references scheme="WWW:LINK">http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data0/bbleh/spring2012/00_dir_roms.ncml.html</dct:references><dct:references scheme="WWW:LINK">http://www.ncdc.noaa.gov/oa/wct/wct-jnlp-beta.php?singlefile=http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data0/bbleh/spring2012/00_dir_roms.ncml</dct:references><dct:references scheme="OPeNDAP:OPeNDAP">http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data0/bbleh/spring2012/00_dir_roms.ncml</dct:references><dct:references scheme="OGC:WMS">http://geoport-dev.whoi.edu/thredds/wms/usgs/data0/bbleh/spring2012/00_dir_roms.ncml?service=WMS&amp;version=1.3.0&amp;request=GetCapabilities</dct:references><dct:references scheme="UNIDATA:NCSS">http://geoport-dev.whoi.edu/thredds/ncss/usgs/data0/bbleh/spring2012/00_dir_roms.ncml/dataset.html</dct:references><dct:references scheme="file">http://geoport-dev.whoi.edu/thredds/fileServer/usgs/data0/bbleh/spring2012/00_dir_roms.ncml</dct:references><dc:relation/><dct:modified>2016-01-07</dct:modified><dct:abstract>Barnegat Bay run driven by ADCIRC tides on the boundaries, realistic river forcing with low-passed elevation from Espresso on the boundaries. Atmospheric forcing is from the NAM model, using the new bathymetry.</dct:abstract><ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326" dimensions="2"><ows:LowerCorner>39.44 -74.44</ows:LowerCorner><ows:UpperCorner>40.14 -74.0</ows:UpperCorner></ows:BoundingBox></csw:SummaryRecord>
```

**Comment by kring** [comment]
You need to run `gulp` or `gulp release` after the npm install.  Is that the problem, maybe?  I'll see if I can get anywhere with the geoport server today.

**Comment by kring** [comment]
Also change the `terriajs-cesium` version in `package.json` to 1.15.4.

**Comment by kring** [comment]
@rsignell-usgs I changed TerriaJS to use the exact query you posted above, and still the geoport.whoi.edu server is timing out (502, proxy error).  Is your ipython notebook above recent?  If not, does it still work?

In any case, I just pushed the change to the `cswReferences` branch, in case it's a problem where it just doesn't work from Australia or something, and it will work for you.

**Comment by rsignell-usgs** [comment]
@kring , I changed the `terriajs-cesium` version in `package.json` to `1.15.4` and now I'm getting:

```
[21:00:56] Finished 'release-specs' after 261 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/home/testbed/map/node_modules/terriajs-cesium/package.json'
```

**Comment by kring** [comment]
`ulimit -n 2048`

https://github.com/TerriaJS/terriajs/wiki/Problems-and-Solutions#emfile-error

**Comment by rsignell-usgs** [comment]
@kring, Woohoo, it's working again!


Thanks for knocking it over the wall to win the game!

**Comment by rsignell-usgs** [comment]
@kring, is the CSW functionality working in the newui current master?

This URL: http://nationalmap.gov.au/#build/TerriaJS/test/init/csw.json brings up a CSW folder, but it seems to be empty:

**Comment by rsignell-usgs** [comment]
My bad.  I just needed to scroll down.  I didn't notice because nothing _appeared_ to happen when I clicked the CSW drop down arrow.

**Pull request merged**
