### PR TITLE
Fix ci and expose locale trait for table columns

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes CI

This PR is targeting `next-fix-ci` branch feel free to change to `next` if think that it is better (this includes all changes from #5253). Everything is done according to the recommendation in https://github.com/TerriaJS/terriajs/pull/5253#issuecomment-782620714

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by tephenavies** [comment]
@zoran995 This fixes our current CI problem (if you switch $1,500 & A$1,500 in specs), but I don't really want to add the ability to set locale in traits for number formatting. We should probably follow the browser's locale settings for all formatted numbers.

**Comment by zoran995** [comment]
We might leave in the description that it is recommended to not define the locale and leave it to browser default (in eastern Europe countries there is an issue that most users have default en settings but they should see the results in the specific locale).
We might look into setting a locale for git actions

**Comment by tephenavies** [comment]
I've decided to disable the 2 tests that fail due to being run in an unexpected locale, so I will close this PR for now. If this feature is important outside of CI tests can you open an issue describing the problem it solves so we can discuss further? Thanks

**Comment by zoran995** [comment]
@steve9164 there is already some discussion in #4191 regarding returning the date in a specific locale based on the language. This PR went in little different direction, in my opinion better option would be to have possibility setting output locale based on language.

**Pull request closed without merging**
