### PR TITLE
Move RelatedMaps to terriajs - powered by config

### LINKED ISSUE #3847: Make related maps load from a config file
Related maps should load from a config file so that we can have correct related maps for all instances.

### PR DESCRIPTION
**Pull request by nf-s**
### Move RelatedMaps to terriajs

Fixes https://github.com/TerriaJS/terriajs/issues/3847

TerriaMap PR to merge after this is merged and TerriaJS release: https://github.com/TerriaJS/TerriaMap/pull/619

Example config - https://gist.githubusercontent.com/nf-s/210a1c0d559a80e9f27994155cef7324/raw/6be92992396b1950e7767805f661f3136288e4f3/related-maps-config.json

Defines 2 related maps - NationalMap and NSW Digital Twin

```json
{
  "initializationUrls": [
    "http://ci.terria.io/main/init/simple.json"
  ],
  "parameters": {
    "relatedMaps": [
      {
        "imageUrl": "https://terria-catalogs-public.storage.googleapis.com/misc/related-maps/nationalmap.jpg",
        "url": "http://nationalmap.gov.au/",
        "title": "NationalMap",
        "description": "The NationalMap is a website for map-based access to spatial data from Australian government agencies. It is an initiative of the Australian Government's Department of the Prime Minister and Cabinet and the software has been developed by Data61 working closely with the Department of the Prime Minister and Cabinet, Geoscience Australia and other government agencies."
      },
      {
        "imageUrl": "https://terria-catalogs-public.storage.googleapis.com/misc/related-maps/nsw-dt.png",
        "url": "http://nsw.digitaltwin.terria.io/",
        "title": "NSW Spatial Digital Twin",
        "description": "The NSW Spatial Digital Twin aims to respond to the NSW State Infrastructure Strategy by developing a 4D (3D+time) Foundation Spatial Data Framework. The goal is to help the NSW Government with infrastructure assets planning and management, integration with land use planning, data collaboration, and sharing."
      }
    ]
  }
}
```

#### Link with example config

http://ci.terria.io/related-map-config/#configUrl=https://gist.githubusercontent.com/nf-s/210a1c0d559a80e9f27994155cef7324/raw/6be92992396b1950e7767805f661f3136288e4f3/related-maps-config.json

#### Link with empty related maps

http://ci.terria.io/related-map-config/#configUrl=https://gist.githubusercontent.com/nf-s/7dc35ae10f8333cae68bbc19eabe0bbe/raw/9f434f81273238b6931588e8cbc0b061f7e69679/config-with-no-related-maps.json

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [x] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by mwu2018** [comment]
@nf-s  Will there be any breaking changes to DT's? DT's use a different mechanism to set their related maps.

**Comment by nf-s** [comment]
> @nf-s Will there be any breaking changes to DT's? DT's use a different mechanism to set their related maps.

No shouldn't be any breaking changes.

As each clone of `TerriaMap` will need to merge this PR to change to new `RelatedMaps` config - https://github.com/TerriaJS/TerriaMap/pull/619

If that PR isn't merged, then `RelatedMaps` will remain unchanged

**Review by mwu2018 — CHANGES_REQUESTED** [review]
Please update CHANGES.md.

**Comment by nf-s** [comment]
> Please update CHANGES.md.

Done!

**Review by mwu2018 — APPROVED** [review]

**Pull request merged**
