### PR TITLE
catalog btn blue on open

### PR DESCRIPTION
**Pull request by chloeleichen**
Fixes https://github.com/TerriaJS/terriajs/issues/1868

### CODE REVIEW

**Comment by RacingTadpole** [comment]
I'm just clarifying the issue over at #1868. But with this PR I can get a lot of highlighted blue bars in the navigation pane, which looks a bit confusing. Eg.
image

**Comment by chloeleichen** [comment]
yeah because they are all 'open', do we want to high light the top level that is open? 

Previously the highlight happens when the button is focused, that is why only one group can be highlighted at all time. 

Maybe it's a question for @philipgrimmett

**Comment by kring** [comment]
Groups should only be blue when they're focused/selected.  But the catalog should remember which group was focused/selected when you close and reopen the catalog UI.  It currently does that for catalog _items_ but not for catalog _groups_.  If that's unclear, stop by and I'll show you what I mean.

**Comment by chloeleichen** [comment]
ah I see, let me give it another go

**Comment by chloeleichen** [comment]
Ready for another look please! @RacingTadpole

**Pull request merged**
