### PR TITLE
Mobx: fix feature highlighting for imagery layers

### LINKED ISSUE #4093: Mobx: feature highlighting not working for imagery layers
Add http://services.ga.gov.au/gis/rest/services/GA_Surface_Geology/MapServer and click somewhere.

On master there is a white highlight around the picked region:
image

On mobx there is only the location marker:
image

### PR DESCRIPTION
**Pull request by mgcsls**
Fixes #4093.

image

### CODE REVIEW

**Comment by mgcsls** [comment]
Note that I didn't quite understand what was going on with the original `removeCallback` and `_highlightPromise` stuff in https://github.com/TerriaJS/terriajs/blob/mobx/lib/Models/GlobeOrMap.ts#L234-L253 but removing it doesn't seem to cause any problems. (It doesn't seem necessary for `this.terria.overlays.remove(catalogItem)` to wait for `catalogItem.loadMapItems()` to finish first. May be wrong though.)

(Also, I did initially try to keep that bit of code the same and just replace the `catalogItem.setTrait(CommonStrata.user, "show", true/false);` lines with `this.terria.overlays.add/remove(catalogItem);`, but that didn't quite work- it caused feature highlights to appear as expected, but not disappear afterwards.)

**Comment by rowanwins** [comment]
~~So I think this needs more work. I suspect the `removeCallback` stuff was around if you make 2 quick clicks - with the current PR things get confused and don't work.~~

I've re-added the removeCallback as per master and it now seems more stable for quick clicks on big polys

**Comment by rowanwins** [comment]
Note that with two quick clicks on big polygons there seems to be something quirky going on, I get a squillion logs to the console along the lines of 

````
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.marker-color is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value GeoJsonCatalogItem@2059.name is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.stroke is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.stroke-width is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.stroke is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.stroke is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value GeoJsonCatalogItem@2059.name is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.marker-opacity is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.fill is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value GeoJsonCatalogItem@2059.name is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value GeoJsonCatalogItem@2059.clampToGround is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.marker-url is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.stroke-opacity is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.fill-opacity is being read outside a reactive context. Doing a full recompute
VM692 react_devtools_backend.js:6 [mobx] Computed value Model@3388.fill-opacity is being read outside a reactive context. Doing a full recompute
`````

This may be related to https://github.com/TerriaJS/terriajs/issues/4126

**Comment by nf-s** [comment]
Merged into https://github.com/TerriaJS/terriajs/pull/6030

**Pull request closed without merging**
