### PR TITLE
Tsify workbench

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #<insert issue number here if relevant>

Moving workbench to styled-components and typescript. This depends on #5342.

For testing this, basically, try adding every possible dataset and verify that workbench is correct.

Some of the changes, although most of them are just move to typescript and styled components
- No longer use calculated height in workbench, let flex do this
- Changed checkbox in item visibility to use checkbox component instead of a button
- chart selector uses a checkbox
- Time section now fills the entire width
- Fixed some small issues identified while working on this that I no longer recall

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist) - existing tests pass succesfully
-   [ ] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by zoran995** [comment]
Some of the elements are converted to flex layout to avoid using calculated height in the workbench.

**Comment by zoran995** [comment]
@steve9164, @nf-s 
Any thoughts on this, is it possible to review this in its current form, or should be split into multiple PR, as there are changes in pretty much every workbench segment? If it is even interesting for reviewing?
I should manage to get some time in the following week to resolve merge conflicts (first to get on board with everything I changed 😆) and maybe try to split some of the code into separate PR. This fixes some small issues like #6091 which I never listed anywhere 😱.

**Comment by tephenavies** [comment]
This PR looks great. We should be able to review it without splitting it up.

**Comment by zoran995** [comment]
@steve9164 I believe this is ready for review. Some files are left as jsx and are using sass but I would leave them for separate PR

**Comment by tephenavies** [comment]
@philipgrimmett 
Left is always new Zoran workbench

1. Bold search placeholder text
image
2. Slightly different text size and spacing on Remove All and Collapse All
image
3. Different spacing of enabled/disabled checbox, different padding above and below item name, larger text size Opacity label
image
4. Border around an item in the workbench
image
5. Difference in padding around explaining text for Terrain side selector, smaller text in terrain selector, light grey background for not-selected terrain selector options, smaller padding between split screen mode box and the first item in the workbench
image
6. White text in date picker, differences in padding
image
7. Text colour, padding
image
8. Padding
image
9. Less dead space at the bottom of the workbench when the workbench has a scrollbar
image
10. Lost the colour of checkbox for chart, and the section the checkbox is in now has rounded corners
image
11. Name no longer wraps
image

**Comment by steve9164** [comment]
@zoran995 This list of visual differences is to speed up design review of this branch. Some of these differences will require fixing (like point 10 - checkbox colour for chart in workbench), others we'll do a UX review and work out what should be done.

**Comment by tephenavies** [comment]
@zoran995 This list of visual differences is to speed up design review of this branch. Some of these differences will require fixing (e.g. points 10 & 11- checkbox colour for chart in workbench and item name wrap), others we'll do a UX review and work out what should be done.

Likely we'll keep some of the changes (e.g. I think the padding changes pointed out in points 7 & 8 make the date picker look better) and probably others we'll decide that neither `main` nor this branch are the best user experience and make some small changes while we're merging this.

**Comment by zoran995** [comment]
@steve9164 I have fixed point 11
image

Have also updated the look of the TerrainSide (when I run this branch again text was black and it was unreadable small), so it now looks like this
image

couldn't replicate point 10 locally 
image

**Comment by philipgrimmett** [comment]
Thanks @zoran995 and @steve9164! Notes/suggestions based on the style comparison above:

>_1. Bold search placeholder text_

For consistency we should apply regular font weight for the search field text

>_2. Slightly different text size and spacing on Remove All and Collapse All_

Set minimum font size to 12px to ensure legibility.

Related (if not to this PR): 
- the workbench header bar feels strangely cramped. Suggested spacing and styling pictured below.
- This is a fragile layout, which I’m hoping will be resolved in the next round of proposed design changes.

dataWorkbench

>_3. Different spacing of enabled/disabled checkbox, different padding above and below item name, larger text size Opacity label_

Suggested spacing below (note 48px height and border for dataset header)

workbenchData

>_4. Border around an item in the workbench_

Would be good to reapply the border/outline in Right image, but not critical.

>_5. Difference in padding around explaining text for Terrain side selector, smaller text in terrain selector, light grey background for not-selected terrain selector options, smaller padding between split screen mode box and the first item in the workbench_

- Reapply min text sizes (12px) and padding from Right image (Done)
- Terrain selector background colour: technically the styling in the Left image is more consistent (progressively lighter background for nested components), but less accessible (poor contrast). Compare is being updated soon, so probably fine to accept new styling.

>_6. White text in date picker, differences in padding_

Styling should be consistent across all form fields in the workbench. Next round of proposed design changes will address this, but for now styling in the Left image is fine.

>_7 and 8. Text colour, padding_

- Keep text styling in left image
- The time selector should be anchored to the workbench time field. Removal of excess padding in Left image is an improvement, but the right padding is still off.

>_9. Less dead space at the bottom of the workbench when the workbench has a scrollbar_

Looks good, keep changes.

>_10. Lost the colour of checkbox for chart, and the section the checkbox is in now has rounded corners_

Restore checkbox colour, keep rounded corners (provided they are consistently applied across all workbench components) (done)

>_11. Name no longer wraps_

Already fixed (thanks Zoran!)

**Comment by nf-s** [comment]
Not sure if this matters or not - but I think quite a few of these visual changes are due to https://github.com/TerriaJS/terriajs/pull/6147#discussion_r810756040

**Comment by zoran995** [comment]
@nf-s yeah some of the changes are due to update of normalize, most importantly #6180 since most of the buttons use RawButton, @philipgrimmett should I restore `cursor: pointer` on button hover so user have an idea it's clickable

1. don't know why it is bold on steve image but it is not on my end

image

3. I made it to be consistent with implementation in main
> Set minimum font size to 12px to ensure legibility.
> Related (if not to this PR):
> - the workbench header bar feels strangely cramped. Suggested spacing and styling pictured below.
Over the entire terria 5px padding/margins is used so it might be good to keep it consistent for now (although I am a fan of 2px rule) 

height 56px - IMHO it takes to much screen
image
height 40px with 10px padding
image
height 40px with 5px padding - consistent with search field and buttons above
image

>>7 and 8. Text colour, padding
> - Keep text styling in left image
> - The time selector should be anchored to the workbench time field. Removal of excess padding in Left image is an improvement, but the right padding is still off.

Not sure what to do about this, might be better to complete this in separate PR since this is pretty consistent with implementation in `main`

This now look like this
image
image

**Comment by philipgrimmett** [comment]
> should I restore `cursor: pointer `on button hover so user have an idea it's clickable

Yep, pls make whatever changes are required to communicate that active buttons are clickable. We should be more consistent for hover states across the app (that's on me), but as a general rule I would suggest toggling brightness +/- 10.

> 1. don't know why it is bold on @steve9164 image but it is not on my end

Are you both using the same browser? I've had issues with font rendering across different browsers in the past.

> 3. I made it to be consistent with implementation in main

Probably the best approach in the short term, apologies for any confusion. I've tried to consistently apply a soft 8px grid with 4px vertical baseline across all Terria UI component designs, but we haven't managed to implement this in code yet (details here https://github.com/TerriaJS/terriajs/issues/3185#issuecomment-457071209). My suggested specs for the header bar will be more relevant for future UI changes, but for this PR 40px height with 5px padding looks good, thanks!

Re. typography in Terria: it needs some love. I'll be applying the following type system across all future Terria prototypes (borrowed from tailwindCSS), but I haven't formally proposed that we implement it yet: https://www.figma.com/file/CG3kj6Fn82yC6nPphULp1w/Terria-Library---Foundation?node-id=18%3A1951 

I expect the type system will be addressed as part of a broader discussion we're currently having around how to make Terria component styling more consistent and maintainable. As always, we'd love to get your thoughts/feedback on this  :)

Thanks again for all of your help @zoran995, looking forward to catching up to discuss Compare v2!

**Comment by zoran995** [comment]
> Are you both using the same browser? I've had issues with font rendering across different browsers in the past.

Chrome, Firefox, and Edge on my end (latest versions), and all of them are showing normal font weight

**Comment by zoran995** [comment]
fixed button cursor, so it is `pointer` again. Also opened a #6200 with just that fix

Let me know if this need anything else

**Comment by tephenavies** [comment]
Planning to merge this on 27th May - after some important demos.

**Comment by zoran995** [comment]
@steve9164 I will plan to merge upstream few days before then and resolve merge conflicts

**Comment by zoran995** [comment]
@steve9164 conflicts are resolved and this is ready for final review/merge

**Comment by tephenavies** [comment]
Thank you so much for this. I love the new look of workbench items. It was unfortunate timing that the normalize update gave some false positives on negative UX changes when we last had the capacity to review this.

**Review by tephenavies — APPROVED** [review]

**Pull request merged**
