### PR TITLE
Make WMS layer name more obvious in catalog item info, plus explain what WMS is

### PR DESCRIPTION
**Pull request by stevage**
Inspired to do this after trying to explain to a user how to figure out what layer to access for a given WMS dataset.

### CODE REVIEW

**Comment by stevage** [comment]
screenshot 2015-07-16 16 21 24

Belatedly @hilarycinis @philipgrimmett

**Comment by hilarycinis** [comment]
oh nice addition. 
We will add your technological distinctiveness to our own...

**Comment by kring** [comment]
Great, thanks!  FYI I made three small tweaks:
- Fixed the style of `<p>` tags to be sensible, rather than using explicit `<br />` tags.
- Made the wikipedia link open in a separate tab.
- Updated `CHANGES.md`.

**Comment by stevage** [comment]
> Fixed the style of `<p>` tags to be sensible, rather than using explicit `<br />` tags.

Hooray.

> Made the wikipedia link open in a separate tab.

Nice.

> Updated CHANGES.md.

Oops.

**Pull request merged**
