### PR TITLE
Mobx themeify

### PR DESCRIPTION
**Pull request by soyarsauce**
### What this PR does

Addresses
https://github.com/TerriaJS/de-australia-map/issues/47
https://github.com/TerriaJS/de-africa-map/issues/44

### Checklist

-   [x] unit test n/a
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by soyarsauce** [comment]
image

**Comment by soyarsauce** [comment]
~Let's just get this merged and refine as we go @steve9164~ actually I will consolidate a few little things first

**Comment by soyarsauce** [comment]
Alright @steve9164 that'll do, take a gander and let me know

**Comment by zoran995** [comment]
one short note, when adding user data the arrow is missing from "select file type" selector

**Comment by soyarsauce** [comment]
Thanks @zoran995 good pickup - that's addressed now

**Review by tephenavies — APPROVED** [review]

**Pull request merged**
