### PR TITLE
Modularised all the things

### LINKED ISSUE #1662: New UI: Preview panel is not scrollable
When the dataset preview+info is too long to fit on one page, there's no scrollbar to let you see the rest of it.  I saw this is in a production deployment of Terrarium, but presumably it happens everywhere.

### PR DESCRIPTION
**Pull request by AlexGilleran**
- Modularised the remaining unmodularised components (explorer panel, charts)
- Split the non-module SCSS files into "common" (which are referenced by the module SCSS) and "global" (which consist of global styles like the leaflet ones and are included globally).
- Fixed drag and drop legends.

Fixes #1662

This isn't completely tested for analytics as I'm not sure where to find a server to test it against...

### CODE REVIEW

**Comment by AlexGilleran** [comment]
OK properly tested analytics and this absolutely mangles it, don't merge yet.

**Comment by AlexGilleran** [comment]
Have now fixed all the analytics things, this is mergeable :D

**Comment by kring** [comment]
@chloeleichen you're probably the best person to review this one.

**Comment by chloeleichen** [comment]
looks good to me

**Pull request merged**
