### PR TITLE
Add chart disclaimers to mobx

### PR DESCRIPTION
**Pull request by tephenavies**
### What this PR does

Fixes https://github.com/TerriaJS/de-australia-map/issues/49

This PR ports the chart disclaimer to mobx.

### Checklist

-   [x] There are no unit tests
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by tephenavies** [comment]
Test with http://ci.terria.io/mobx-7-10-chart-disclaimer/#https://gist.githubusercontent.com/steve9164/4f9ccbc29388ae3b9408d6f902488439/raw/bef3f7ab026fead21dd24ed418b877fe1c2b30de/test-wms-chartDisclaimer.json

Add the item "Test chartDisclaimer", then click this button:
image

You should see the chart disclaimer!

**Review by rowanwins — COMMENTED** [review]
- [x] Perhaps just change the trait to something more logical
- [x] And check the left padding on the disclaimer

**Review by rowanwins — APPROVED** [review]
Looks good!

**Review by soyarsauce — CHANGES_REQUESTED** [review]
I thought @steve9164 said there were problems with this, and that it isn't ready?

**Comment by tephenavies** [comment]
Sorry. Forgot to make this a draft PR after I discovered its shortfalls.

This PR allows you to add a disclaimer to any time-series item by setting the `chartDisclaimer` trait. This will show a disclaimer at the top of the chart panel when any `chartItems` of that item are displayed in the chart panel. However the specific use case the `chartDisclaimer` system was made for is a situation where a WMS creates a chart from a feature info template (using `<chart>`). 

To support that I think we should use the system proposed in this PR but add `chartDisclaimer` as a trait to feature info templates, a parameter to the `<chart>` tag, or similar and pass that `chartDisclaimer` through to the created csv item that creates the chart.

**Comment by soyarsauce** [comment]
@stevage heya I'm unclear where this is at now, for the purposes of getting the disclaimer available via whatever mechanism on a dea layer, are we there? Or do you want to take it to the featureinfo trait level first?

**Comment by soyarsauce** [comment]
@steve9164 heya I'm unclear where this is at now, for the purposes of getting the disclaimer available via whatever mechanism on a dea layer, are we there? Or do you want to take it to the featureinfo trait level first?

**Comment by tephenavies** [comment]
It's almost done using chart attribute -> CSV Trait to pass the chart disclaimer from a feature info template in a `<chart>` tag to the expanded chart CSV. Current blockers are:
- when I tested this a couple of days ago I couldn't find the attribute being passed through
- the chart PR (that has just been merged) which might require that I refactor this (very minor changes needed) to only apply to CsvCatalogItem

**Comment by soyarsauce** [comment]
Cool, could you pick it up on Monday so we have time to get it out for the DEA delivery?

**Comment by tephenavies** [comment]
Moved to #4536.

**Pull request closed without merging**
