### PR TITLE
Zoom on enable

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #5836

Add `zoomOnEnable` to mappable traits. When it's true, zoom to the item when it's added to workbench

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] ~~I've updated relevant documentation in `doc/`.~~
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by ykiu** [comment]
This is nice.

**Comment by malnajdi** [comment]
will this be merged in next release ? also what about isEnabled ?

**Comment by na9da** [comment]
Hey @zoran995 - Thanks for fixing this :hearts: 

It looks good to me, however I suggest changing the trait name to `zoomOnAddToWorkbench` as it makes it clear that the zoom happens only when the item is added to workbench and not on show/hide.

@malnajdi - did you mean what is the equivalent for `isEnabled` trait in v8? That would be the `show` trait.

**Comment by malnajdi** [comment]
@na9da - What i want to do is on loading the terriaMap i want to show 2 default layers that they should be showing all time.
It seems the v7 converter tool creates a list called workbench and it contains all ids of the layers need to be presented. 

But isn't there a way to do it like the version7 ?

**Comment by zoran995** [comment]
Hi @na9da good point for name, updated

**Review by na9da — APPROVED** [review]

**Comment by na9da** [comment]
Hi @malnajdi - the `isEnabled` behavior of auto adding to workbench is deprecated in v8. Adding to the workbench array is the way to do it. I'm assuming it was removed because of conflicting behavior with stories and share URLs.

**Pull request merged**
