### PR TITLE
Mobx UI fixes

### LINKED ISSUE #3889: Compass doesn't work in mobx
No errors thrown but it doesn't rotate

### PR DESCRIPTION
**Pull request by rowanwins**
Fixes compass indicator moving in mobx

And fixes the basemap name which initially displays as `(None)`

Resolves #3889
Resolves https://github.com/TerriaJS/nsw-digital-twin/issues/184

### CODE REVIEW

**Review by soyarsauce — CHANGES_REQUESTED** [review]
Cool - but doesn't seem to work?
Steps to reproduce:
1. load http://ci.terria.io/mobx-ui-fixes/
2. drag compass
3. observe errors:
image

**Comment by rowanwins** [comment]
Not sure why CI is so unhappy :(

**Comment by soyarsauce** [comment]
CI is fixed now

**Comment by soyarsauce** [comment]
But now there's conflicts 🤔 @rowanwins the pleasure is all yours to resolve 🙏 thanks

**Review by soyarsauce — APPROVED** [review]

**Pull request merged**
