### PR TITLE
improve look of timeline

### PR DESCRIPTION
**Pull request by chloeleichen**
screen shot 2016-08-29 at 10 39 16 am

### CODE REVIEW

**Comment by chloeleichen** [comment]
@RacingTadpole 😄

**Comment by RacingTadpole** [comment]
thanks Chloe!
I know this isn't the fault of this PR but any chance you could fix up Travis by fixing these three warnings too?

```
/home/travis/build/TerriaJS/terriajs/lib/ReactViews/Feedback/FeedbackForm.jsx
  70:13  warning  'feedbackFormClassNames' is never reassigned. Use 'const' instead  prefer-const
/home/travis/build/TerriaJS/terriajs/lib/ReactViews/Notification/MapInteractionWindow.jsx
  18:13  warning  'windowClass' is never reassigned. Use 'const' instead  prefer-const
/home/travis/build/TerriaJS/terriajs/test/ReactViews/FeatureInfoSectionSpec.jsx
  308:17  warning  'template' is never reassigned. Use 'const' instead  prefer-const
```

**Comment by rdengate** [comment]
@RacingTadpole They are fixed in https://github.com/TerriaJS/terriajs/pull/1994, maybe we should merge that.

**Comment by RacingTadpole** [comment]
excellent, thanks @rdengate. I've just merged it, and this with master.

**Comment by rdengate** [comment]
thanks @RacingTadpole!

**Comment by RacingTadpole** [comment]
nice! I'll merge this - but another thought @chloeleichen - any idea why the date labels don't line up with the ticks?

**Comment by chloeleichen** [comment]
no idea but it should. I'll look into it

**Pull request merged**
