### PR TITLE
Fixed issue #2524

### PR DESCRIPTION
**Pull request by kennib**

### CODE REVIEW

**Comment by kring** [comment]
Thanks @kennib!  There are a few places that use `SearchBox`, though, and none of them pass in a `currentViewer` prop.  Rather than teaching `SearchBox` - a low-level component - about viewers, I think it would make sense to use the existing `onClear` prop function.  Some of the places that use `SearchBox`, like `MobileHeader`, already pass in an `onClear` function and you only need to add the `notifyRepaintRequired` to the existing callback (which is easy in `MobileHeader` because it has a `terria` prop from which you can get the `currentViewer`).  In other places (`SidePanel` for example) you'll need to add a new `onClear` attribute, but again it'll be easy to call `notifyRepaintRequired` because you have access to `this.props.terria`.

**Comment by kennib** [comment]
@kring is this better?

**Comment by kring** [comment]
Yeah a bit better @kennib.  But the method is `notifyRepaintRequired` not `notifyRepaint`, and it's on `terria.currentViewer` not directly on `terria`.  And you're going to have problems with `this` being the wrong thing if you pass `this.props.terria.currentViewer.notifyRepaintRequired` directly as the onClear attribute without a `bind`.

It looks like maybe you haven't been able to get set up to the point where you can run TerriaMap and try it out?  Can I help with that somehow?

**Comment by kennib** [comment]
I think the issues I was having are with parts of the build persisting. So it works on my version of the map, but only because it was working before.

**Comment by kring** [comment]
That's strange.  Why don't you put into slack when you get a chance and we can figure it out.

**Comment by kennib** [comment]
@kring I've fixed my build and the changes are hopefully good now.

**Comment by kring** [comment]
This looks good, thanks @kennib!  Would you mind fixing your git history so that it's associated with your GitHub account (or just add the email address in the commit to your GitHub account) and then sign the CLA?

**Pull request closed without merging**
