### PR TITLE
Add option for automatically opening Add Data at startup

### LINKED ISSUE #1960: Option to automatically open Add Data at startup
NEII would prefer the new UI to automatically pop open the "add data" when users first visit the site. Do we have an option (eg in config.json) for that? Could we?

### PR DESCRIPTION
**Pull request by mgcsls**
Resolves #1960, but note that this won't actually do anything until TerriaJS/TerriaMap#406 is also merged.

### CODE REVIEW

**Comment by mgcsls** [comment]
Note that this won't actually do anything until https://github.com/TerriaJS/TerriaMap/pull/406 is also merged.

**Comment by soyarsauce** [comment]
@mgcsls nice! 💯 -  could you update changelog as well? And a reference for the issue being addressed

**Comment by mgcsls** [comment]
Resolves #1960

**Review by soyarsauce — APPROVED** [review]

**Comment by soyarsauce** [comment]
@mgcsls last one - could you add a test for viewState now that I've shown you how to do the tests? To ensure `afterTerriaStarted` behaviour. 💯

**Comment by soyarsauce** [comment]
image

**Pull request merged**
