### PR TITLE
Add Mapbox style catalog item

### PR DESCRIPTION
**Pull request by ctwhome**
### What this PR does

Add Mapbox style catalog item

Adds the ability to load Mapbox styles from https://studio.mapbox.com

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

Test catalog item on TerriaMap init files with:
 ```
{
      "type": "mapbox-style",
      "name": "Pirate - Mapbox Style",
      "username": "tempgeocent",
      "styleId": "cj2qe6qid003a2rmrquvqgbcx",
      "accessToken": "pk.eyJ1IjoidGVtcGdlb2NlbnQiLCJhIjoiY2l1YTNmenEyMDAwdDJ6cWZxbG55Yjg4OSJ9.QRTz4Pi3096MtXKc_QgpWQ"
    },
```

### CODE REVIEW

**Comment by ctwhome** [comment]
Test catalog item on TerriaMap init files with:

```
 {
      "type": "mapbox-style",
      "name": "Mapbox Style",
      "styleId": "ck9b6yhm00cgm1iqsmunkcxi4",
      "accessToken": "pk.eyJ1IjoiY3R3aG9tZSIsImEiOiJjazhpZ3ljOXUwNTR0M2VxbHhkNWl2NDEzIn0.swIehGzH7mS_TiohUmGuAg"
}
```

**Review by tephenavies — CHANGES_REQUESTED** [review]
Hi @ctwhome. Thanks for the pull request! This worked really well once I switched to using https requests to Mapbox.
Before I merge this could you please:
- Add an entry into CHANGES.md
- Add yourself to our CONTRIBUTORS.md file. You can add yourself as a member of an organisation or as an individual contributor. And you can use either your name or your github username if you'd prefer not to put your name.

**Comment by tephenavies** [comment]
Hey @ctwhome. I've [added the changelog entry and added you as a contributor](https://github.com/TerriaJS/terriajs/pull/4317/commits/1404a21eaaa23c39de73bc40f8de51c39832cd0a). If you're happy with that I can merge.

**Comment by ctwhome** [comment]
Thank you Steve, I had it pending to do but thanks for doing it, and for the support! Please merge it

**Review by tephenavies — APPROVED** [review]

**Pull request merged**
