### PR TITLE
Use terriajs-cesium 1.19.0.

### PR DESCRIPTION
**Pull request by kring**

### CODE REVIEW

**Comment by kring** [comment]
Don't merge this yet.  There are lots of deprecation warnings and probably bugs as a result of Cesium making `defined` now equivalent to `definedNotNull`, and deprecating `definedNotNull`.

**Comment by RacingTadpole** [comment]
That's an interesting change. I see the discussion here https://github.com/AnalyticalGraphicsInc/cesium/pull/3522

**Comment by kring** [comment]
Yeah I'm not sure I 100% agree with the change, but probably not worth fighting. :)

**Comment by kring** [comment]
This is ready now.

**Comment by RacingTadpole** [comment]
@AlexGilleran discovered that we distinguish `null` and `undefined` for `tableStyle.timeColumn`.
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CsvCatalogItem.js#L368

I'll update the PR to handle this. However, maybe this is a sign to implement this in a different way...?

**Comment by RacingTadpole** [comment]
Oops - looks like we already had a spec in place for this, and that you've already updated `CsvCatalogItem`, @kring! Thanks. @AlexGilleran - can you replicate the problem you were seeing?

**Comment by RacingTadpole** [comment]
@AlexGilleran: I can replicate the problem. I'm looking into fixing it.

**Comment by AlexGilleran** [comment]
OK great, I was just finding I could still reproduce it and presumed I'd messed up an npm link somewhere :(

**Comment by RacingTadpole** [comment]
Ah, it's a subtle one - we fall afoul of the `defined` check in https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CsvCatalogItem.js#L368 . 

_This means that any `json` that sets a property to `null` will now be ignored._

The [spec](https://github.com/TerriaJS/terriajs/blob/master/test/Models/CsvCatalogItemSpec.js#L307-L316) didn't pick it up because it sets the properties of the tableStyle directly, so doesn't go through `TableStyle`'s `updateFromJson`.

I propose to change https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CsvCatalogItem.js#L368 so that it recognises `null` as distinct from `undefined` again. This will fix the problem for any other `json` properties we've missed, if any.

**Comment by AlexGilleran** [comment]
:shipit:

**Pull request merged**
