### PR TITLE
Allow parent window of an iframe to optionally post messages to a TerriaJS app

### PR DESCRIPTION
**Pull request by kring**
When embedding TerriaJS in an iframe, the parent window has a lot of control over what the embedded app displays by setting its URL, including supplying a full catalog and potentially even entire data files via the `start` URL parameter.  However, the URL tends to get very large very quickly.

This pull request provides an alternative: post JSON to the app via `window.postMessage`.  For example:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>NationalMap Embed Test</title>
</head>

<body>
    <iframe id="embeddedNationalMap" src="http://nationalmap.research.nicta.com.au/kring" width="1024" height="768"></iframe>

    <script type="text/javascript">
        window.addEventListener('message', function(e) {
            if (e.source === document.getElementById('embeddedNationalMap').contentWindow && e.data === 'ready') {
                // NationalMap is ready to receive messages!
                document.getElementById('embeddedNationalMap').contentWindow.postMessage({
                    initSources: [
                        {
                            initialCamera: {
                                "north": -33.827,
                                "east": 151.249,
                                "south": -33.907,
                                "west": 151.165
                            },
                            catalog: [
                                {
                                    type: "group",
                                    name: "Foo",
                                    isPromoted: true,
                                    isOpen: true,
                                    items: [
                                        {
                                            type: "csv",
                                            name: "My Data",
                                            data: "POA,Some Value\n2000,1\n2205,2",
                                            isEnabled: true
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }, 'http://nationalmap.research.nicta.com.au/kring');
            }
        });
    </script>
</body>
</html>
```

In order to enable this feature, applications must call `updateApplicationOnMessageFromParentWindow` right after `terria.start`, typically in `index.js`:

```
updateApplicationOnMessageFromParentWindow(terria, window);
```

### CODE REVIEW

**Comment by RacingTadpole** [comment]
There's a weird Travis error - do you know what's happening there?

**Comment by kring** [comment]
This is fixed now.

**Comment by RacingTadpole** [comment]
Very nice! This works really well. A few thoughts for you: :-)
- Is it worth adding a test? (It would be great, but I don't want to hit you with too much work!)
- Is there a way to remove the existing catalog (like #clean in the URL?)
- Given that your awesome html snippet will get hidden away in a closed pull request soon, can you document how to use this feature? Could either do it in terriajs/tutorials or in the NationalMap wiki. I guess we ought to decide how we manage these alternatives too, one day...

**Comment by kring** [comment]
I added the doc above to the TerriaJS wiki:
https://github.com/TerriaJS/terriajs/wiki/Controlling-TerriaJS-in-an-iframe-by-posting-it-messages

**Pull request merged**
