### PR TITLE
Document making husky work with yarn workspaces

### PR DESCRIPTION
**Pull request by kring**

### CODE REVIEW

**Comment by soyarsauce** [comment]
I did a fresh `yarn install` from TerriaMap with the new documented config

```
:/mnt/e/projects/TerriaMap$ yarn why husky
yarn why v1.15.2
[1/4] Why do we have the module "husky"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "workspace-aggregator-c88d29d7-6b57-48c5-a2a9-2ece71d2dcca#husky@2.2.0"
info Reasons this module exists
   - "_project_#terriajs" depends on it
   - Hoisted from "_project_#terriajs#husky"
   - in the nohoist list ["/_project_/**/husky"]
Done in 0.69s.
```

But it still installs the hooks to .git in TerriaMap, did I miss a step?

**Comment by kring** [comment]
Did you remove your `node_modules` before running `yarn install`? Just running `yarn install` isn't good enough for some reason. That `why` is kind of contradictory, saying it was hoisted _and_ it's in the nohoist list. On my system it doesn't say it was hoisted:

```
rin035@SWAN-EV /mnt/c/github/TerriaMap (master)
$ yarn why husky
yarn why v1.15.2
[1/4] Why do we have the module "husky"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "terriajs#husky@2.2.0"
info Reasons this module exists
   - "_project_#terriajs" depends on it
   - in the nohoist list ["/_project_/**/husky"]
info Disk size without dependencies: "112KB"
info Disk size with unique dependencies: "428KB"
info Disk size with transitive dependencies: "3.35MB"
info Number of shared dependencies: 37
Done in 6.50s.
```

**Comment by soyarsauce** [comment]
Yes I deleted `node_modules` and then `yarn install` - but I've just tried the same on macOS and it did everything as expected this time, husky gets installed under terriajs & hooks to the right repo.

**Comment by soyarsauce** [comment]
I just tried again with windows, and after crashing once, it looks like it worked after I deleted not only `node_modules` in TerriaMap but also terriajs...!

**Review by soyarsauce — APPROVED** [review]

**Pull request merged**
