### PR TITLE
Mobx: various updates to VideoGuide component

### LINKED ISSUE #4359: DEA User testing: Videos missing X to close
We have a generic "video overlay" from both
- welcome message
- help panes

Just need a close button, @vicborgy are you happy if we just use a white-bg-close-in-top-right-corner?

### PR DESCRIPTION
**Pull request by reginapramesti**
### What this PR does

Fixes #4359 https://github.com/TerriaJS/terriajs/issues/4349

* Video modal now has a close button
* Pressing escape on a `VideoGuide` component will now close the component
* Added some unit tests for `VideoGuide` component
* Modified `StoryBuilder` component to use the `VideoGuide` component for the data stories video for consistency (+ reusing components + decreasing sass code little by little!)

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by soyarsauce** [comment]
@reginapramesti hitting escape on the welcome message video now closes both of them, there's an example of escape only closing one thing at a time on http://ci.terria.io/master/ -
1,. open data catalog via add data
2. click a catalog item
3. click share
4. hit escape, only closes share window
5. hit escape again, closes data catalog

**Review by soyarsauce — CHANGES_REQUESTED** [review]
(And i say master here because i now notice that it doesn't do as it should behave on mobx..!)

**Comment by reginapramesti** [comment]
Thanks for that I'll figure out what's wrong with the mobx version

**Comment by soyarsauce** [comment]
@reginapramesti are you happy with this now or still workigno n it?

**Comment by reginapramesti** [comment]
Happy with it now, please review it when you have the time @soyarsauce 😄

**Review by soyarsauce — APPROVED** [review]
Nice work, I hadn't realised you toggle the video based on a `videoGuideVisible` string and makes me feel like we should mount this once and let it render based on that, but we're slipping into the "new modal system" territory by doing that - so we'll leave it alone for now!

**Pull request merged**
