### PR TITLE
Update README.md with Innovisite (France)

### PR DESCRIPTION
**Pull request by tobybellwood**
French fork of TerriaJS, created by @innovisite

### CODE REVIEW

**Comment by kring** [comment]
Looks like someone (Steve?) already added it, possibly since you opened this PR!  Thanks though, @tobybellwood!

**Comment by tobybellwood** [comment]
haha - figured I had to submit a PR at some point - thanks @stevage!

**Comment by kring** [comment]
Don't let the crazy long lead time on this one discourage you in the future, we'll do better next time! :)

**Comment by stevage** [comment]
Heh, yeah, I think you must have opened this PR between the time I tweeted the link and committed the change myself.

**Pull request closed without merging**
