### PR TITLE
Mobx story

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Port #3938 to mobx, using mobx styling ([3938 comment](https://github.com/TerriaJS/terriajs/pull/3938#issuecomment-609525972)). The popup on window close is not in this PR

@vicborgy Is there maybe some newer version of invision for story panel (https://invis.io/KTWPRT8CM82)?
@steve9164 just to check this since some of these changes (with master styling) are already in #4466

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable - **`StoryBuilder` is in `.jsx` format and currently only `.ts | .tsx` test are started. `StoryBuilder` depends on the `react-anything-sortable` which doesn't have types**
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by zoran995** [comment]
Just some quick images of how it looks now. @vicborgy this still misses the new icons for options menu (edit)

**Comment by tephenavies** [comment]
Thanks for the PR. This is with @vicborgy for review.

**Review by tephenavies — APPROVED** [review]

**Comment by tephenavies** [comment]
Thank again @zoran995! I made a couple of small adjustments to the final look of scenes within StoryBuilder. Here's the results
image

**Comment by zoran995** [comment]
@steve9164 thanks for merging this
p.s. is this edit icon correct in the vic initial design it was a pen icon (it is mentioned in above comment, the one with bunch of images)
edit story

**Comment by vicborgy** [comment]
Sorry @zoran995 I missed it. This is not correct, it definitely needs to be the pen icon. Also worth mentioning is that the 'view' icon needs to be replaced as well. Below are the files.
[view-icon.zip](https://github.com/TerriaJS/terriajs/files/5207209/view-icon.zip)
[edit-icon.zip](https://github.com/TerriaJS/terriajs/files/5207211/edit-icon.zip)

**Comment by tephenavies** [comment]
Thanks @vicborgy. I'll ticket those and put them into our sprint to fix them. Should be easy, hopefully 🤞 .

**Comment by zoran995** [comment]
@steve9164 done in #4738

**Pull request merged**
