### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/terriajs/terriajsnext/) for TerriaJS/TerriaJSNext.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by LorenzoStucchi** [comment]
Hi @steve9164, 
Sorry for bothering you, I just would like to inform you that I have completed the translation of the interface in Italian in this PR

**Comment by tephenavies** [comment]
@LorenzoStucchi That's great news! Thanks for your contributions and for letting me know that the translation is complete.

**Review by tephenavies — APPROVED** [review]

**Comment by LorenzoStucchi** [comment]
@steve9164 now the translation works and will it be present in the new version? Or are other changes needed?

**Comment by tephenavies** [comment]
@LorenzoStucchi We haven't enabled any translations by default. Any TerriaMap maker can include translations from the files in TerriaJS (from weblate) from config.json parameters, like:
```json
        "languageConfiguration": {
          "enabled": true,
          "fallbackLanguage": "en",
          "languages": {
            "en": "English",
            "fr": "French"
          }
        },
```
See https://docs.terria.io/guide/customizing/client-side-config/#languageconfiguration.

Do you think we should include finished translations by default when a developer starts a new TerriaMap?

**Comment by LorenzoStucchi** [comment]
@steve9164 Thank you for the explanation, I will insert it in our version. 🚀 

I believe that the insertion of the translation could be something useful, also because the translation regards only the interface, not directly the data, so a translated interface could help more users to navigate the data. However, this is my idea but you are the developers so mine it is just a suggestion 😃

**Comment by LorenzoStucchi** [comment]
> ```json
>         "languageConfiguration": {
>           "enabled": true,
>           "fallbackLanguage": "en",
>           "languages": {
>             "en": "English",
>             "fr": "French"
>           }
>         },
> ```
> 
> See https://docs.terria.io/guide/customizing/client-side-config/#languageconfiguration.

Hi @steve9164, I tried how it is explained but it does not work. I test with French language and works but I believe that is due to the fact that it has been imported and defined here:

https://github.com/TerriaJS/terriajs/blob/62c69365b376eb67f7f38bd10bfc0b4a318ea003/lib/Models/Internationalization.ts#L6

and here:

https://github.com/TerriaJS/terriajs/blob/62c69365b376eb67f7f38bd10bfc0b4a318ea003/lib/Models/Internationalization.ts#L128-L130

Is this the reason?

**Comment by zoran995** [comment]
Hi @LorenzoStucchi
Yes that is why it fails, I thought that it worked for you so didn't jump it before.
Unless building a custom version of terriajs you should be able to add a translation file into the TerriaMap path as  `wwwroot/languages/it/translation.json`. It's the same as for language override files, described here https://docs.terria.io/guide/customizing/translation-guide/#language-files

Either file name should work (translation.json and languageOverrides.json). 
At least I recall it working like that, if no resource bundle is available in compiled application try to load `translation.json` and language override from wwwroot, and if all of that fails fallback to english (same as for missing translations). I just noticed that this part is missing in doc
Sorry if i missed something in your question, writing from phone 

Edit - just tested it, when language is set in config the order of resolving translation files is
1. registered translation resource bundle (in `Internationalization.ts`)
2. if the first step fails we try to load `translation.json` file from `wwwroot/languages/{abbreviation}/translation.json` 
3. after that we try to load `languageOverrides.json` - this file will be requested in all cases (first 2 steps can fail)
image
image

**Comment by LorenzoStucchi** [comment]
Hi @zoran995, I follow your procedure and it work. Thanks 😃 

However, I believe that this procedure is not so intuitive for a generic user, for me, it is more intuitive than when a language is completed it is imported in terriajs and then the user has only to add it in the `config.json` file. For this, I opened a PR #5925 for importing Italian languages but you can close it if this is not the way you would like to proced.

**Comment by tephenavies** [comment]
Sorry, I was wrong. @zoran995 is right, translations won't be loaded from terriajs translations directory, but will be loaded if present at the TerriaMap path `wwwroot/languages/{{lng}}/translation.json`. I think it'd be nice to be able to use translations from terriajs's languages folder without having to build them into the webpack bundle. Maybe the following would work:
* Move translations in terriajs repo from `lib/Language/en/translation.json` to `wwwroot/languages/en/translation.json` (or similar in wwwroot) and then (somehow) pull translations from the either the URL `languages/{{lng}}/translation.json` or `build/TerriaJS/languages/{{lng}}/translation.json` based on an override system (TerriaMap translations override TerriaJS translations)
  * Maybe the override system can be simple. Translations from the `translation` namespace could always come from `build/TerriaJS/languages/{{lng}}/translation.json` (i.e. terriajs repo) and `languageOverrides` could always come from `languages/{{lng}}/languageOverrides.json`

**Comment by zoran995** [comment]
I would leave english in terriajs since we need it for development, while other languages are maintained via weblate. 
Other languages should be added to TerriaMap as `wwwroot/languages/{lang}/translation.json` probably that can be automated like we add translations to terriajs for now.
The rest of the code can stay the same, currently: 
- we try to get translations from internationalization registered bundles
- if that fails then we try to load from `wwwroot/languages/en/translation.json`
- and at the end always try to load from `languages/{{lng}}/languageOverrides.json`

Personally, I don't think we should add more languages to terriajs, and basically what we should do is change a target repo for weblate translations update to TerriaMap (this should be possible see https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate). This should be marked as a breaking change for anyone using terriajs as a library outside of the TerriaMap system (we can also have an option loading translations from github repo).

**Comment by tephenavies** [comment]
@zoran995 I meant that we can move translations from `lib/Language/{{lng}}/translation.json` to `wwwroot/languages/{{lng}}/translation.json` inside the terriajs repo. Then those json files wouldn't be bundled in .js by webpack, but could be fetched by apps from `build/TerriaJS/languages/{{lng}}/translation.json`. TerriaJS specs might need some changes to pick up translations, but other than that it should work.

That is, if we decide to include default translations in terriajs.

**Pull request merged**
