### PR TITLE
fix UserDrawing

### PR DESCRIPTION
**Pull request by hisayan**
### What this PR does

UserDrawing (e.g. Measure tool) point dragging was only working with leaflets, so it should work with cesium as well.

### Test me

Unit test is not available, so please draw a line with Measure tool and drag a point in the middle of the line to see if it moves or not.

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by na9da** [comment]
Hi @hisayan,

Thank you very much for contributing the fix.

Could you please sign the [CLA agreement](https://github.com/TerriaJS/terriajs/pull/6841#issuecomment-1678651043) so that we can action this PR.

Cheeers

**Comment by hisayan** [comment]
@na9da Thanks. I sigined it right now.

**Comment by na9da** [comment]
Hi @hisayan,

These changes look good to me and I have tested it locally.

So that I can merge in your PR, could you please:

- Add a line [here in CHANGES.md](https://github.com/TerriaJS/terriajs/blob/ae08808696dd9bf778b738f70db9b257d3b91cad/CHANGES.md?plain=1#L4) - something like 
    ```md
    #### next release (8.3.3)

    - Fixes broken point dragging interaction for user drawing in 3d-mode.
    - [The next improvement]
   ```
- and add yourselves to the [CONTRIBUTORS.md](https://github.com/TerriaJS/terriajs/blob/ae08808696dd9bf778b738f70db9b257d3b91cad/CONTRIBUTORS.md?plain=1#L64) file

Cheers,
Nanda

**Review by na9da — APPROVED** [review]
Approved.

Thanks @hisayan for the contribution.

**Pull request merged**
