### PR TITLE
Make GyroscopeGuidance ready for i18n

### PR DESCRIPTION
**Pull request by ykiu**
### What this PR does

I noticed some strings in the GyroscopeGuidance component are hardcoded, blocking translation. This patch moves them out of the source code to the i18n message registry.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
    - Unit tests aren't applicable because this patch just adds some strings to translation.json
-   [x] I've updated CHANGES.md with what I changed.
    - I haven't updated CHANGES.md because this patch seems too small to be listed there. I would update it if that's required, however.

### CODE REVIEW

**Review by tephenavies — APPROVED** [review]
Thanks for the contribution!

**Review by tephenavies — CHANGES_REQUESTED** [review]
Actually, could you add a CHANGES.md entry and add yourself to CONTRIBUTORS.md?

**Comment by ykiu** [comment]
OK, edited both files.

**Review by tephenavies — APPROVED** [review]

**Comment by ykiu** [comment]
@steve9164 Thanks!

**Pull request merged**
