### PR TITLE
fixing #1945, use base64 encoding for font

### PR DESCRIPTION
**Pull request by chloeleichen**
Issue: https://github.com/TerriaJS/terriajs/issues/1945

Tested working in all modern browsers. 

Though I cannot test whether this approach actually solve the problem of PM&C not able to use google font. Guess we can put it on staging somewhere and ask them to send a screenshot? 

It seems that it also make gulp watch stops sometimes, i think it's because the css file to watch is too big?

### CODE REVIEW

**Comment by kring** [comment]
I set up a temporary server for this branch:
https://nationalmap-base64-font.nationalmap.nicta.com.au/

I'll ping some folks in the government to send us a screenshot.

**Comment by kring** [comment]
Here's what it looks like for @tobybellwood:
image

Still default fonts @chloeleichen?

**Comment by chloeleichen** [comment]
nope, looks great! tho did you notice the preview map looks very strange @kring 

No it doesn't i was lying

**Comment by kring** [comment]
Latest screenshot:
image

I've asked for a screenshot with the Add Data panel open, but it looks good so far!

**Comment by chloeleichen** [comment]
Maybe we should ask for a screenshot(again) with add data panel open and a preview open? 👯

**Comment by kring** [comment]
Looks like it's working!

image

**Comment by chloeleichen** [comment]
Yay! looks good to me!

**Comment by kring** [comment]
Toby says he can now see the icons on fontawesome too!  So apparently something has changed such that custom fonts are no longer blocked.  That's good in general, but makes it hard to tell if this change is accomplishing anything.  

Here's a side-by-side screenshot:
image

**Comment by chloeleichen** [comment]
but we fixed fontawesome icon (we no longer use fontawesome icons) from ages ago?

**Comment by kring** [comment]
Right, fontawesome is just a way to test if custom fonts are supported, because it's super obvious on that site when they're not.

**Comment by kring** [comment]
Ok here we have side-by-side images on a system confirmed not to be able to show custom fonts (at least on fontawesome):

Without this change:
image

With this change:
image

They look the same to me. :(

**Comment by chloeleichen** [comment]
no good :(

**Pull request closed without merging**
