### PR TITLE
Major refactoring of guide.jsx

### LINKED ISSUE #4306: Onboarding v2 - Satellite imagery guide "slider-in-help-panel"
The amazing help panel framework needs to be modified to allow "slider" mode, where you supply an array of slides and it shows that in the panel instead of the video+content.

The content can be found in `lib/ReactViews/Guide/satelliteGuideData.js`

image

### PR DESCRIPTION
**Pull request by reginapramesti**
### What this PR does

Fixes #4306 

Refactored Guide.jsx to make it usable in help panel. Removed sass and modified the old design to match new designs.

### Checklist

-   [x] n/a for now. There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by soyarsauce** [comment]
image
titles seem to no longer render

**Comment by soyarsauce** [comment]
...because of the new required property - got it

**Review by soyarsauce — CHANGES_REQUESTED** [review]
Seems great @reginapramesti ! As part of this PR, could you fix all the proptype and key errors (just open console when you load the build and you'll see them all onload) - this PR adds even more of them so I wanna stay on top of them 🙂

**Comment by reginapramesti** [comment]
~~I've fixed the errors relating to guide, and I'll resolve the rest of the errors as part of the main UI tweaks in https://github.com/TerriaJS/terriajs/issues/4294 (already included another bullet point)~~

Edit: I've figured out all of the key errors now, so that's done!

**Pull request merged**
