### PR TITLE
Mobx: Ensure there aren't more bins than unique values

### LINKED ISSUE #4325: Mobx: Sometimes scalar legends on table data have more bins than values
If the number of unique values in a dataset is very low and there in no `numberOfBins` set in `TableColorStyleTraits` then you can end up with some funky presentation, eg

ScalarBins

### PR DESCRIPTION
**Pull request by rowanwins**
### What this PR does

Fixes #4325

This PR ensures there aren't more bins than there are unique values.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by nf-s** [comment]
Poor `@computed` getting linked into everything...
I am pretty happy with this, but I think we could make improvements to the colour ramp - for example
image
This has picked two colours which are quite similar, whereas it should have used a light yellow, and deep red.
Maybe we could use https://github.com/d3/d3-scale-chromatic to generate colour scales based on number of bins

**Review by nf-s — CHANGES_REQUESTED** [review]
See https://github.com/TerriaJS/terriajs/pull/4326#issuecomment-673240839

**Comment by nf-s** [comment]
Or, we could start using this approach instead https://github.com/TerriaJS/terriajs/pull/3667

**Comment by soyarsauce** [comment]
Related https://github.com/TerriaJS/terriajs/issues/4263

**Comment by nf-s** [comment]
We have decided to leave continuous colour ramps for another day, I will clean this up and merge it as a quick fix

**Review by nf-s — APPROVED** [review]

**Pull request merged**
