### PR TITLE
Issue 988 proxy Url for legend

### PR DESCRIPTION
**Pull request by tephenavies**
@kring issue https://github.com/TerriaJS/terriajs/issues/988. Legend Urls are proxied in LegendSectionViewModel.show(), but that could be moved to the constructor if that would be a better place.

### CODE REVIEW

**Comment by chloeleichen** [comment]
@steve9164 please sign the CLA

**Comment by kring** [comment]
@steve9164 yeah that's not the right place to do it.  The constructor won't work either.  In both cases, the list of proxied URLs won't be updated if the list of legendUrls changes (which can and does happen when new information comes in asychronously).

Instead, use `knockout.defineProperty` in the constructor to define a proxiedLegendUrls property.  It will just return the `map` that you currently have in `show`.  The difference is that a knockout property keeps track of the fact that it depends on the `legendUrls` property, and will be recomputed when `legendUrls` changes.

**Comment by tephenavies** [comment]
@kring Ok. I didn't realise that the legendUrls changed.

**Comment by kring** [comment]
@steve9164 no worries.  TerriaJS is crazy: everything can change! :)

**Comment by chloeleichen** [comment]
Oh this is my fault i told @steve9164 to put it there :(

**Comment by kring** [comment]
@chloeleichen it was a reasonable suggestion, but using `knockout.defineProperty` is better.

**Comment by tephenavies** [comment]
@kring Is that better? Should I do any caching of the proxiedLegendUrls, or is having them recalculated every time okay?

**Comment by kring** [comment]
Yep, much better, thanks!  You don't need to cache because Knockout will do that automatically.

Two more things:
- Can you add a note to CHANGES.md?  Something like "Legend URLs are now accessed via the proxy, if applicable."
- Nitpick: please use spaces for indentation instead of tabs.  A lot of us use [Sublime Text](http://www.sublimetext.com/3), which will do that automatically based on the `.editorconfig` file in the root TerriaJS directory.

**Comment by tephenavies** [comment]
I added the changelog entry, converted the tabs into spaces and fixed the tab setting on my editor.

**Comment by kring** [comment]
Thanks @steve9164!

**Pull request merged**
