### PR TITLE
Update a prompt text in DataPreview

### PR DESCRIPTION
**Pull request by ykiu**
### What this PR does

The functionality of adding multiple datasets at once by pressing ctrl/shift is great, but is hard to discover.

This commit improves the message displayed in the DataPreview to make the feature more discoverable.

### Test me

Launch TerriaMap and see if the message is appropriate.

image

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
  - unit tests are not applicable because there're no changes to the code
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Review by nf-s — CHANGES_REQUESTED** [review]
Hi @ykiu 

Thanks for making this PR!
Sorry it has taken us so long to review it.

I have a few comments

- Can you please replace the `"+"` with the plus icon?
  - image
  - You should be able to use `<Icon glyph={Icon.GLYPHS.add} />` 
- Can you please change "Ctrl or Shift" to just "Shift". Ctrl doesn't work on mac, and Shift should work on all platforms

Let me know what you think, thanks 🙂

**Comment by ykiu** [comment]
Thanks @nf-s , that way it looks nicer. I've updated the PR and also reorganized the relevant parts of the dictionaries so that they are easier to work with for translators. By the way I'm not a native speaker of English so please feel free to correct the English message I added, if it sounds weird.

image

**Review by nf-s — APPROVED** [review]
Thanks so much @ykiu !

Sorry for the delay in review. This is a great improvement 🙂

**Comment by ykiu** [comment]
@nf-s Thank you!

**Pull request merged**
