### PR TITLE
New user interface

### PR DESCRIPTION
**Pull request by kring**
image

This is the new user interface, as designed by @philipgrimmett.  Try it out here:
http://nationalmap.research.nicta.com.au/demo/

We could keep tweaking this forever - and we have plans to change/improve a number of things - but it's already better than the existing UI, so that justifies a pull request and even deploying it to Production.

In addition to the new UI (and significant changes to how the UI is coded), this pull request also renames all of the old view-models (like `WebMapServiceItemViewModel`) and puts them in the `Models` directory instead of the `ViewModels` directory.  I used to think it made sense to call them view-models, mostly because they used Knockout, but as I started writing the actual view-models for the new UI it became apparent that I was thinking of them incorrectly.  They're really National Map's model layer.

### CODE REVIEW

**Comment by hilarycinis** [comment]
Thanks heaps Kevin, Keith and Phil.

I've started a review which I will complete this week - let me know the format you'd prefer (git issues, one combined email...)

Also, just want to say Phik has done an outstanding job with design, interaction states, application of ux recommendations as well as CSS directly in to tweak fonts and the like. Remebering Phil is still new to nicta, we are his first serious gig out of uni and I have to say he has more than stepped up :)

Hil

Hilary Cinis
Principal UX & Designer
UX & Design Manager
NICTA

On 21 Jan 2015 19:41, Kevin Ring notifications@github.com wrote:

[image]https://cloud.githubusercontent.com/assets/924374/5833234/01c09756-a1a5-11e4-9351-ef1253df9dc9.png

This is the new user interface, as designed by @philipgrimmetthttps://github.com/philipgrimmett. Try it out here:
http://nationalmap.research.nicta.com.au/demo/

We could keep tweaking this forever - and we have plans to change/improve a number of things - but it's already better than the existing UI, so that justifies a pull request and even deploying it to Production.

In addition to the new UI (and significant changes to how the UI is coded), this pull request also renames all of the old view-models (like WebMapServiceItemViewModel) and puts them in the Models directory instead of the ViewModels directory. I used to think it made sense to call them view-models, mostly because they used Knockout, but as I started writing the actual view-models for the new UI it became apparent that I was thinking of them incorrectly. They're really National Map's model layer.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/NICTA/nationalmap/pull/489

Commit Summary
-   Start implementing new UI.
-   Merge remote-tracking branch 'origin/master' into phil-ui
-   New UI starting to come together...
-   Show Loading/no items messages.
-   Merge remote-tracking branch 'origin/master' into phil-ui
-   CSS and I don't get along.
-   Add checkboxes and drop-down arrows.
-   Fix alignment of icons with rows.
-   Merge remote-tracking branch 'origin/master' into phil-ui
-   Highlight enabled items.
-   Info buttons, arrows on top-level groups.
-   Fix jshint warnings.
-   Update Info icon.
-   Fix spacing of right-edge icons.
-   Add a manifest file.
-   Show app without chrome on iOS too.
-   Add padding around group's children.
-   Brand bar improvements.
-   Some styling of search box.
-   Add panel open/close icons.
-   Basic Now Viewing hookup.
-   Fix jshint warnings.
-   Hook up Clear All button.
-   Show a message when Now Viewing is empty.
-   Merge remote-tracking branch 'origin/master' into phil-ui
-   Add legend/opacity to Now Viewing tab.
-   Improve appearance of credits.
-   Keep "Clear All" fixed at top of Now Viewing.
-   Tweak Now Viewing interactions.
-   Use new search icon.
-   Add Remove button to Now Viewing panel.
-   Add tooltips and make search icon smaller.
-   Add menu bar.
-   Knockoutify the menu bar.
-   Add lat/lon/elevation display.
-   Hide lat/lon display in Leaflet (for now).
-   WIP distance legend.
-   Merge remote-tracking branch 'origin/master' into phil-ui
-   Add distance legend.
-   Don't show scale in bold.
-   Add Navigation controls.
-   Fix tilt, and move SVGs.
-   Hook up catalog item info panel.
-   Hook up info from Now Viewing tab, too.
-   Now Viewing tweaks.
-   Add popup messages.
-   WIP share popup.
-   Fix jshint warning.
-   Fix another jshint warning.
-   Displace map instead of overlaying it.
-   Make the explorer panel smaller.
-   Animate map resize on show/hide explorer panel.
-   Ease out the map show/hide animation.
-   Improved tab styling.
-   Tweak close button opacity transition.
-   Fix transition when switching tabs while panel closed.
-   Use a different transition for the collapse button.
-   Fix jshint warnings.
-   Tab switch animation.
-   Fix scrollbar nonsense.
-   Don't let long URLs escape their containers.
-   Start with "National Data Sets" open.
-   Don't cut off Info icon on Macs, hopefully.
-   Catalogue -> Data Catalogue
-   Speed up Explorer panel hide/show.
-   Basic search-as-you-type for locations.
-   Zoom to first search result on enter.
-   Fix jshint warning.
-   Use the correct culture in Bing Maps geocode requests.
-   Better display of location search results.
-   Use correct locale for Bing location searches.
-   Improve search result country handling.
-   Allow search culture to be specified.
-   Make Australian locations visually distinct.
-   Eliminate duplicate zoom-to code.
-   Fix jshint warnings.
-   Add Gazetteer search.
-   Basic support for catalogue searching.
-   Much better catalogue search results.
-   Don't show top level groups in search results.
-   Allow messages to be collapsed, too.
-   Fix Gazetteer search.
-   Report initial viewer (2D/3D) to Google Analytics.
-   Style the Cesium feature info popup.
-   Create Add Data panel.
-   Make the Add Data panel shorter.
-   Make Add Data via URL work, with basic autodetection.
-   Inform the user about the conversion service.
-   Support adding a local data file.
-   Eliminate duplicate code.
-   Overhaul Add Data panel.
-   List GPX on the Add Data panel.
-   Prompt when auto requires the conversion service.
-   Merge remote-tracking branch 'origin/master' into phil-ui-tweaks2
-   Fix cut of settings panel.
-   Indicate when the Settings panel is active.
-   Progress toward base map selection.
-   Fix jshint warning.
-   Keep the base map on the bottom.
-   Really keep the base map on the bottom.
-   Add all the base layers.
-   Hook up Share panel.
-   Improve distance legend in Leaflet.
-   Don't show the Tilt button in 2D.
-   Fix printing.
-   Remove old SearchPanel.
-   Remove old code.
-   A few tweaks.
-   Fix imagery feature picking.
-   Focus the search box when activating the tab.
-   Move a bunch of files around.
-   Start renaming the non-view-models.
-   More renames of former view-models.
-   Finish up renaming.
-   Re-add support for drag/drop.
-   Show feedback on drag/drop.
-   Resize Leaflet on explorer panel hide/show.
-   CSS cleanup.
-   Changed location bar font weight
-   Fix bug preventing modals from closing in IE11.
-   Fix size of Add Data URL input box in IE11.
-   Make the UI appear above the map in IE9.
-   Make WMS and WFS GetCapabilities work in IE9.
-   Fix GeoJSON loading in IE9.
-   Show error message on IE8.
-   Don't show the tilt button when initially using Leaflet.
-   Inform the user if browser is incapable of add local files.
-   Fix TableDataSource in IE9.
-   Standardised font sizes and families
-   Keep the timeline/animation controls above the map.
-   More IE9 compatibility.
-   The Explorer Panel should not block map input when it's closed.
-   Working Now Viewing reordering, with some minor quirks.
-   Eliminate most of the reordering quirks.
-   Make drag/drop work on more browsers.
-   Remove some old code.
-   Add CompositeCatalogItem instead of using CatalogGroup hackily.
-   Actually add CompositeCatalogItem.
-   Don't make entire "Remove All" toolbar clickable, just the text.
-   Typography and colour tweaks
-   Merge remote-tracking branch 'pg/phil-ui-tweaks2' into phil-ui
-   Merge pull request #487 from philipgrimmett/phil-ui-tweaks2
-   Merge pull request #488 from NICTA/phil-ui-tweaks2
-   Fix Now Viewing menu when scrollbars appear.
-   Give legends a max width and make them direct links to the image.

File Changes
-   M gulpfile.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-0 (23)
-   M package.jsonhttps://github.com/NICTA/nationalmap/pull/489/files#diff-1 (3)
-   D public/images/AustralianHydrography.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-2 (0)
-   D public/images/AustralianTopography.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-3 (0)
-   D public/images/BingMapsAerial.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-4 (0)
-   D public/images/BingMapsAerialWithLabels.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-5 (0)
-   D public/images/BingMapsRoads.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-6 (0)
-   D public/images/NASABlackMarble.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-7 (0)
-   D public/images/NaturalEarthII.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-8 (0)
-   A public/images/australian-topo.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-9 (0)
-   A public/images/bing-aerial-labels.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-10 (0)
-   A public/images/bing-aerial.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-11 (0)
-   A public/images/bing-maps-roads.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-12 (0)
-   A public/images/black-marble.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-13 (0)
-   A public/images/gov-brand.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-14 (0)
-   A public/images/hydro.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-15 (0)
-   A public/images/natural-earth.pnghttps://github.com/NICTA/nationalmap/pull/489/files#diff-16 (0)
-   M public/index.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-17 (124)
-   A public/manifest.jsonhttps://github.com/NICTA/nationalmap/pull/489/files#diff-18 (5)
-   A spec/ViewModels/CsvCatalogItemSpec.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-19 (170)
-   D spec/ViewModels/CsvItemViewModelSpec.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-20 (170)
-   R spec/ViewModels/WebMapServiceCatalogItemSpec.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-21 (16)
-   R src/Core/KnockoutSanitizedHtmlBinding.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-22 (0)
-   A src/Core/createFragmentFromTemplate.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-23 (15)
-   A src/Core/loadView.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-24 (36)
-   A src/Core/registerKnockoutBindings.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-25 (24)
-   M src/Map/TableDataSource.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-26 (6)
-   R src/Models/Application.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-27 (146)
-   R src/Models/ArcGisMapServerCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-28 (32)
-   A src/Models/BingMapsCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-29 (129)
-   R src/Models/Catalog.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-30 (42)
-   R src/Models/CatalogGroup.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-31 (148)
-   R src/Models/CatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-32 (353)
-   R src/Models/CatalogMember.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-33 (92)
-   A src/Models/Cesium.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-34 (92)
-   R src/Models/CkanCatalogGroup.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-35 (100)
-   A src/Models/CompositeCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-36 (84)
-   R src/Models/CsvCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-37 (174)
-   R src/Models/CzmlCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-38 (60)
-   R src/Models/GeoJsonCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-39 (82)
-   R src/Models/GpxCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-40 (88)
-   R src/Models/ImageryLayerCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-41 (106)
-   R src/Models/KmlCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-42 (66)
-   A src/Models/Leaflet.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-43 (72)
-   R src/Models/Metadata.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-44 (16)
-   R src/Models/MetadataItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-45 (12)
-   R src/Models/ModelError.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-46 (8)
-   R src/Models/NowViewing.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-47 (80)
-   R src/Models/OgrCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-48 (94)
-   A src/Models/Services.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-49 (7)
-   R src/Models/ViewerMode.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-50 (0)
-   R src/Models/WebFeatureServiceCatalogGroup.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-51 (97)
-   R src/Models/WebFeatureServiceCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-52 (128)
-   R src/Models/WebMapServiceCatalogGroup.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-53 (105)
-   R src/Models/WebMapServiceCatalogItem.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-54 (116)
-   A src/Models/addUserCatalogMember.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-55 (58)
-   A src/Models/createCatalogItemFromFileOrUrl.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-56 (76)
-   R src/Models/createCatalogItemFromUrl.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-57 (16)
-   R src/Models/createCatalogMemberFromType.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-58 (12)
-   R src/Models/raiseErrorOnRejectedPromise.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-59 (0)
-   R src/Models/raiseErrorToUser.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-60 (6)
-   A src/Models/registerCatalogMembers.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-61 (59)
-   A src/Styles/AddDataPanel.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-62 (160)
-   A src/Styles/BrandBar.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-63 (49)
-   A src/Styles/CatalogItemInfo.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-64 (125)
-   A src/Styles/Core.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-65 (88)
-   A src/Styles/DataCatalogTab.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-66 (111)
-   A src/Styles/DistanceLegend.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-67 (26)
-   A src/Styles/DragDrop.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-68 (16)
-   A src/Styles/ExplorerPanel.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-69 (197)
-   A src/Styles/Floating.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-70 (24)
-   A src/Styles/LocationBar.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-71 (26)
-   A src/Styles/Map.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-72 (89)
-   A src/Styles/MenuBar.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-73 (39)
-   A src/Styles/Navigation.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-74 (50)
-   A src/Styles/NowViewingTab.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-75 (151)
-   A src/Styles/Panels.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-76 (4)
-   A src/Styles/PopupMessage.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-77 (34)
-   A src/Styles/Reset.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-78 (47)
-   A src/Styles/SearchTab.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-79 (134)
-   A src/Styles/SettingsPanel.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-80 (87)
-   A src/Styles/SharePopup.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-81 (54)
-   A src/SvgPaths/svgArrowDown.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-82 (1)
-   A src/SvgPaths/svgArrowRight.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-83 (1)
-   A src/SvgPaths/svgCheckboxChecked.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-84 (1)
-   A src/SvgPaths/svgCheckboxUnchecked.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-85 (1)
-   A src/SvgPaths/svgCollapse.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-86 (1)
-   A src/SvgPaths/svgInfo.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-87 (1)
-   A src/SvgPaths/svgMenu.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-88 (1)
-   A src/SvgPaths/svgReset.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-89 (1)
-   A src/SvgPaths/svgTilt.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-90 (1)
-   A src/SvgPaths/svgZoomIn.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-91 (1)
-   A src/SvgPaths/svgZoomOut.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-92 (1)
-   A src/ViewModels/AddDataPanelViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-93 (187)
-   A src/ViewModels/BaseMapViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-94 (11)
-   A src/ViewModels/BingMapsSearchProviderViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-95 (163)
-   A src/ViewModels/BrandBarViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-96 (41)
-   A src/ViewModels/CatalogItemInfoViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-97 (45)
-   A src/ViewModels/CatalogItemNameSearchProviderViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-98 (85)
-   D src/ViewModels/CesiumViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-99 (17)
-   A src/ViewModels/DataCatalogTabViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-100 (41)
-   A src/ViewModels/DistanceLegendViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-101 (144)
-   A src/ViewModels/DragDropViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-102 (135)
-   A src/ViewModels/ExplorerPanelViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-103 (67)
-   A src/ViewModels/ExplorerTabViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-104 (27)
-   A src/ViewModels/GazetteerSearchProviderViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-105 (122)
-   D src/ViewModels/LeafletViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-106 (11)
-   A src/ViewModels/LocationBarViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-107 (176)
-   A src/ViewModels/MenuBarItemViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-108 (32)
-   A src/ViewModels/MenuBarViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-109 (18)
-   A src/ViewModels/NavigationViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-110 (265)
-   A src/ViewModels/NowViewingTabViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-111 (190)
-   A src/ViewModels/PopupMessageViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-112 (51)
-   A src/ViewModels/SearchProviderViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-113 (25)
-   A src/ViewModels/SearchResultViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-114 (35)
-   A src/ViewModels/SearchTabViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-115 (85)
-   D src/ViewModels/ServicesViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-116 (7)
-   A src/ViewModels/SettingsPanelViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-117 (67)
-   A src/ViewModels/SharePopupViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-118 (111)
-   D src/ViewModels/registerCatalogViewModels.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-119 (59)
-   D src/ViewModels/runWhenDoneLoading.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-120 (31)
-   A src/Views/AddDataPanel.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-121 (51)
-   A src/Views/BrandBar.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-122 (13)
-   A src/Views/CatalogItemInfo.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-123 (117)
-   A src/Views/DataCatalogTab.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-124 (52)
-   A src/Views/DistanceLegend.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-125 (4)
-   A src/Views/DragDrop.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-126 (5)
-   A src/Views/ExplorerPanel.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-127 (22)
-   A src/Views/LocationBar.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-128 (11)
-   A src/Views/MenuBar.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-129 (23)
-   A src/Views/Navigation.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-130 (14)
-   A src/Views/NowViewingTab.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-131 (54)
-   A src/Views/PopupMessage.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-132 (11)
-   A src/Views/SearchTab.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-133 (71)
-   A src/Views/SettingsPanel.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-134 (22)
-   A src/Views/SharePopup.htmlhttps://github.com/NICTA/nationalmap/pull/489/files#diff-135 (31)
-   M src/main.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-136 (267)
-   A src/main.lesshttps://github.com/NICTA/nationalmap/pull/489/files#diff-137 (69)
-   M src/viewer/AusGlobeViewer.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-138 (519)
-   D src/viewer/GeoDataBrowser.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-139 (244)
-   D src/viewer/GeoDataBrowserViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-140 (840)
-   D src/viewer/GeoDataInfoPopup.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-141 (163)
-   D src/viewer/NavigationWidget.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-142 (231)
-   D src/viewer/PopupMessage.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-143 (56)
-   D src/viewer/SearchWidget.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-144 (132)
-   D src/viewer/SearchWidgetViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-145 (306)
-   D src/viewer/ServicesPanel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-146 (161)
-   D src/viewer/SharePanel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-147 (84)
-   D src/viewer/TitleWidget.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-148 (54)
-   D src/viewer/TitleWidgetViewModel.jshttps://github.com/NICTA/nationalmap/pull/489/files#diff-149 (44)
-   M third_party/cesiumhttps://github.com/NICTA/nationalmap/pull/489/files#diff-150 (2)

Patch Links:
-   https://github.com/NICTA/nationalmap/pull/489.patch
-   https://github.com/NICTA/nationalmap/pull/489.diff

—
Reply to this email directly or view it on GitHubhttps://github.com/NICTA/nationalmap/pull/489.

---

The information in this e-mail may be confidential and subject to legal professional privilege and/or copyright. National ICT Australia Limited accepts no liability for any damage caused by this email or its attachments.

**Comment by kring** [comment]
> I've started a review which I will complete this week - let me know the format you'd prefer (git issues, one combined email...)

If you have any showstopper issues (things we _must_ fix before putting this in front of customers), add them directly to this issue.  If you think you might have any issues like that, make a note of that here ahead of time so we don't merge this before all that feedback is in.

If you have design or style suggestions, I'll leave it to Phil how he'd most like to receive them.  GitHub issues make sense to me, but if it's lots of little things it might be easier to put a bunch in one GitHub issue or even an email.

For (non-critical) bugs or feature requests, GitHub issues would be great.

> Also, just want to say Phik has done an outstanding job with design, interaction states, application of ux recommendations as well as CSS directly in to tweak fonts and the like.

No question, thanks Phil!

**Comment by hilarycinis** [comment]
“Settings” - please to change to “Maps” until more content is added in justifying a settings grouping

The map selection panel needs a close button or other indication of exiting. For now, an “x” action in the top right as the toggle action isn’t really clear and clicking off the panel can interfere with the map interactions
maps

“Now Viewing” - add a counter badge to indicate response to loading data (see mock)
- states are:
  -- the badge appears on selection of a data set
  -- the badge disappears on viewing the Now Viewing pane.
  -- the badge appears on subsequent data set selections
  -- the badge disappears on subsequent viewing the Now Viewing pane.

nowviewing

“Now Viewing” - open the most recent layer (at the top) current is stays closed while the first layer added remains open. This is prohibitive to feedback about a successful addition of a data set.

LHS Menu Panel - orient hide/show arrow up and down to anticipate the direction the panel moves in. (see mocks)
menu2
menu1

**Comment by hilarycinis** [comment]
I will discuss a formal user testing approach for feedback with the group in the next meeting.

**Comment by kring** [comment]
> Settings” - please to change to “Maps” until more content is added in justifying a settings grouping

Done.

> The map selection panel needs a close button or other indication of exiting.

Added a close button, and also made clicking outside the panel close it.  

> “Now Viewing” - add a counter badge to indicate response to loading data (see mock)

Ok, working on this next.  Phil and I were discussing yesterday that a counter that just always shows the total number of datasets might be preferable to one that shows the "new since you last visited the tab" datasets.  But that choice won't change my implementation much so we can try it both ways and see what we like best.

> “Now Viewing” - open the most recent layer (at the top) current is stays closed while the first layer added remains open. This is prohibitive to feedback about a successful addition of a data set.

Done.

> LHS Menu Panel - orient hide/show arrow up and down to anticipate the direction the panel moves in. (see mocks)

This seems much more confusing to me, since the panel slides in from the left.  Are you sure?

**Comment by hilarycinis** [comment]
> > “Now Viewing” - add a counter badge to indicate response to loading data (see mock)
> > 
> > Ok, working on this next. Phil and I were discussing yesterday that a counter that just always shows the total number of datasets might be preferable to one that shows the "new since you last visited the tab" datasets. But that choice won't change my implementation much so we can try it both ways and see what we like best.

HC The primary reason for the counter is to communicate there is something to look at in the Now Viewing panel, not really to communicate how many things. But its polite to count them :) 
As long as there is something bright and noticeable to draw attention to the tab heading and instigate a feeling of investigation by the user (not just a same text size and colour count) but a proper badge pattern then I am flexible about the behavioural nuances. Happy to go with your implementation and see how it goes, thanks for discussing it more. 

> > LHS Menu Panel - orient hide/show arrow up and down to anticipate the direction the panel moves in. (see mocks)
> > This seems much more confusing to me, since the panel slides in from the left. Are you sure?

HC ah ok, this animation (in chrome) has changed from top/bottom to left/right, so you are correct to leave it as is :)

**Comment by hilarycinis** [comment]
BTW this is coming together so nicely, I am so excited about it going live.

**Comment by kring** [comment]
@hilarycinis all of your requested changes are done and live:
http://nationalmap.research.nicta.com.au/demo/

The Now Viewing badge has a "popping" animation when its number increases.  It doesn't pop when the number of now viewing items decreases.

**Comment by hilarycinis** [comment]
Outstanding!!!

**Comment by hilarycinis** [comment]
ok... I just did a quick usability test on my test monkey (husband). He totally overlooked the badge as he was watching the map for the data. He also just told me he did't even think about why the data vis (eg broadband) was a mixture of colours ... so he's not looking for a legend. When I suggested a legend appearing over on the right on loading the data layer, that explained the legend then he agreed it would have helped him understand the data and then he said he would have to be able to "move" it so it didn't get in the way. This is by no way conclusive only to point out we need another round of user testing especially around this topic.

To be honest, I'm happy the legend is slightly buried until we have a more useful legend communication (eg programatically or updated and useful legends)

**Comment by kring** [comment]
Well... two ideas:
1. Call attention to the New Viewing tab more strongly by animating the entire clicked dataset flying toward the Now Viewing tab and then shrinking into it.
2. Show a little helpful popup the first time a user enables a dataset.  "You just added a dataset to your map.  Head over to the Now Viewing tab to see its legend, adjust its opacity, and more."

I think either of these, or whatever else we come up with, can happen after we roll what we have so far out to Production though.

**Comment by hilarycinis** [comment]
yeah agreed. Had thought of the first suggestion, that's nice but a little popup pointing at the Now Viewing with a note might be nice and fits with some other tip type things in the pipeline. 

Cool :)

**Comment by kring** [comment]
So... Does anyone know of any remaining problems that should prevent this from being merged and deployed to Production?

**Comment by hilarycinis** [comment]
I'm fine with the current implementation, Phil?

Any improvements we can do after its live I think.

Hil

On 27 Jan 2015 16:36, Kevin Ring notifications@github.com wrote:

So... Does anyone know of any remaining problems that should prevent this from being merged and deployed to Production?

—
Reply to this email directly or view it on GitHubhttps://github.com/NICTA/nationalmap/pull/489#issuecomment-71592367.

---

The information in this e-mail may be confidential and subject to legal professional privilege and/or copyright. National ICT Australia Limited accepts no liability for any damage caused by this email or its attachments.

**Comment by philipgrimmett** [comment]
I'd like to do one more pull request with fixes for the all of the modal styles and 'Search' in Safari/Firefox. There are a bunch of other small changes I still want to make, but nothing that needs to be done before deployment.

**Comment by kring** [comment]
Ok sounds good.  BTW the search styles are fixed.  Check it out in the staging server.

**Comment by kgrochow** [comment]
2D appears to be dead.

**Comment by kgrochow** [comment]
All the populate-cache functionality is missing.  Where does that live now?

**Comment by kgrochow** [comment]
There appears to be no way get a timeline toappear for csv files in a share link.

**Comment by kgrochow** [comment]
The startup performance checking code is all commented out.  Why?

**Comment by kring** [comment]
> The startup performance checking code is all commented out. Why?

It kept popping up on my (reasonably fast) machine.  I think the two second warmup is too long given that the globe only continues rendering for one second on mouse movement now.  I'm not sure yet the best way to fix it, so I've commented it out for now.

> 2D appears to be dead.

Oops, fixed now.  This was caused by my incomplete commenting-out of the frame rate monitoring code.

> All the populate-cache functionality is missing. Where does that live now?

It was in a part of the GUI that is gone now.  I'll need to reintroduce it, probably as a separate UI component.

> There appears to be no way get a timeline toappear for csv files in a share link.

Good catch!  This is now fixed, in that you can click on a dataset or on the "Zoom To" link to make the timeline appear and make it show the right interval.

**Comment by kgrochow** [comment]
I'd like to get the performance stuff in and start getting feedback as soon as possible across more machines.  Let's put it back in and set it to 1.0  Do you have the 'slow' machines available for testing?

**Comment by kgrochow** [comment]
I think we should go ahead and merge, try on stage the rest of today and post it live tomorrow.

**Comment by kring** [comment]
Sounds good!

**Pull request merged**
