### PR TITLE
Upgrade to Leaflet 1.3.1.

### PR DESCRIPTION
**Pull request by kring**

### CODE REVIEW

**Comment by kring** [comment]
@steve9164 do you mind taking a look at this?

**Review by tephenavies — COMMENTED** [review]
I've updated my _onClick monkey-patch (it was missing feature ordering logic and was also throwing exceptions)

**Review by tephenavies — APPROVED** [review]

**Comment by tephenavies** [comment]
Merge this when/if you're happy with my changes to the _onClick function. (It's not a great way to keep it updated, but I don't think there's another way to do it other than a fork of Leaflet)

**Comment by kring** [comment]
Thanks @steve9164!

**Pull request merged**
