### PR TITLE
Tsify styled components

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #<insert issue number here if relevant>

Most of the styled-components are written in javascript and not in TS so we have to import them using CJS format. This is a beginning to tsify them and move import to the ES module format. This need to go through an iterative process to determine the best rules enforcement since some options should not be allowed together as they will only confuse users.

I might also propose some of the changes to the styled-components (non-UI related) but to enforce more strict rules (i.e. button themes/types `primary`, `secondary`).

p.s. Upgrade to TypeScript v4 would enable us to write more strict types checks (i.e. for styledWidth) using [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by tephenavies** [comment]
Thanks @zoran995. I've wanted to get this done for a while now.

Those template literal types look odd. It's super cool what they'll allow us to do for Box & similar though. We're tracking our upgrade to Typescript 4 in #5219, which at the moment is waiting on support for accessors overriding properties (fixing TS2611 errors).

**Comment by zoran995** [comment]
After doing a little investigation probably the best is to go with this as is and incrementally improve components. There is a bunch of places that components are overridden with custom style.

We might get inspiration for components from [Atlassian design system](https://atlassian.design/components/select/examples) (they are using styled-components)  ([source](https://bitbucket.org/atlassian/atlaskit-mk-2)). Also https://bitbucket.org/atlassian/design-system-mirror/src/master/design-system/

Also, the styled-system looks nice https://styled-system.com/. 
@steve9164 Is there a plan for terria to support multi-theme UI?

**Comment by tephenavies** [comment]
Finally merging! Sorry for the delay.

I like the look of styled-system.

I'm not sure what you mean by multi-theme UI. Could you expand on that?

**Comment by zoran995** [comment]
i.e. light/dark UI option for the user to choose between, or some other color themes

**Comment by AnaBelgun** [comment]
That's interesting @zoran995 and it might be connected by our Theme-ing ticket / thinking https://github.com/TerriaJS/terriajs/issues/4661; feel free to comment / suggest options.

**Comment by tephenavies** [comment]
@zoran995 It is possible to dynamically switch themes by setting `props.themeOverrides` on `StandardUserInterface`.

**Comment by zoran995** [comment]
My idea was mainly should we go in direction to provide a possibility for end users of the application an option to choose from predefined color schemes (button in UI), in that case we would need to support multiple themes at the same time.

**Pull request merged**
