### PR TITLE
Mobx measure tool

### PR DESCRIPTION
**Pull request by soyarsauce**
@mgcsls has ported the measure tool to mobx!

### CODE REVIEW

**Comment by soyarsauce** [comment]
Resolves https://github.com/TerriaJS/terriajs/issues/3476

**Comment by tephenavies** [comment]
@mgcsls Can you investigate why it doesn't show on http://ci.terria.io/mobx-measure-tool/ 
Also there's something weird going on with the map settings panel:

image

**Comment by soyarsauce** [comment]
@steve9164 it won't appear until terriamap-mobx re-enables the measure tool

**Comment by soyarsauce** [comment]
& map settings thing seems to be on `mobx`-'master'

**Comment by soyarsauce** [comment]
> Also there's something weird going on with the map settings panel:

btw this existed before this PR

**Pull request merged**
