### PR TITLE
  Fixes FeatureInfoPanel port from #4240 & some wrong proptypes

### PR DESCRIPTION
**Pull request by soyarsauce**
### What this PR does

Fixes FeatureInfoPanel port from https://github.com/TerriaJS/terriajs/pull/4240 & some wrong proptypes

### Checklist

-   [x] no unit tests for port/type update
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by soyarsauce** [comment]
Yeah definitely don't merge this until I fix feature info panel

**Comment by soyarsauce** [comment]
merged mobx now so should be good to go

**Review by na9da — APPROVED** [review]
Looks good!

There is some code here that uses the [old prop for FeedbackButton](https://github.com/TerriaJS/terriajs/blob/mobx-update-versions/lib/ReactViews/StandardUserInterface/MapColumn.jsx#L138), but it is commented out, so not a problem.

**Comment by soyarsauce** [comment]
Yeah we'll probably slowly clean up those commented out bits when we get to removing sass (as a requirement for https://github.com/TerriaJS/terriajs/blob/mobx/doc/contributing/styled-components-and-sass.md)

**Pull request merged**
