### PR TITLE
Basemap json config

### PR DESCRIPTION
**Pull request by JJediny**

### CODE REVIEW

**Comment by JJediny** [comment]
DO NOT PULL... Placeholder for Issue #907 

Approach for discussion is to extend CatalogItem w two new variables in `isBasemap` and `thumbnailUrl`. isBasemap to be used as a variable within an `item` as it avoids defining a new BaseMapModel and avoids creating a new highlevel filter to separately handle a new process for readJson for both `Basemap` and `Catalog`. This way [CompositeCatalogItem](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CompositeCatalogItem.js) need only be modified or emulated with a new model for Basemap that only sets an item when isBasemap = True...

Does this make sense - also not confident with my JavaScript skills on the next/best step?

**Comment by kring** [comment]
Thanks @JJediny!  As we've discussed before, I do think it's reasonable to add a `thumbnailUrl` to `CatalogItem`.

However, I'm not so sure about the `isBasemap` bit.  It seems like you're heading toward a pattern where TerriaJS would search through the entire catalog to find all the base maps, and populate the base map selector from that.  But that concerns me on two fronts:
- it requires that all base maps be in the catalog, and
- it will take a long time, and generate lots of requests, to search through the entire catalog.

I think it would be better to add a new section to the JSON init file, `baseMaps`, to explicitly define the list of basemaps.  It can be deserialized in the same way as `catalog` so it shouldn't take more than a few lines of code to do it.

Does that sound reasonable?

**Comment by JJediny** [comment]
Absolutely... Wasn't sure if catalog would be filtered once and parse out basemaps concurrently - but if it would require an additional iteration over catalog items then completely agree... I'll take another stab but it might be helpful If we can schedule a quick google hangout to knock it out in ~20 or so next week?

**Comment by kring** [comment]
> Wasn't sure if catalog would be filtered once and parse out basemaps concurrently

We load sections of the catalog on demand.  For example, if a group is populated by querying a CKAN server, we don't query the CKAN server until the group is opened.  If we made the assumption that base layers would only be found in non-delay-loaded groups, performance would be fine.  But we'd still have the first problem I mentioned above.

>  it might be helpful If we can schedule a quick google hangout to knock it out in ~20 or so next week

Ok, I'll email you!

**Comment by rsignell-usgs** [comment]
@kring & @JJediny , did indeed some offline (google hangout) progress take place?

**Comment by kring** [comment]
@JJediny I'm going to close this for now, but feel free to re-open when something new needs review or discussion.

**Pull request closed without merging**
