### PR TITLE
Organize models

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

This is mostly as an idea, it should be further discussed how to properly group files in folders. Main reason was grouping the new model related classes and functions, sometimes it's hard to find exactly what is needed.  Some of the files in Models directory, isn't used anywhere in codebase 
```
calculateImageryLayerIntervals.js
computed-evaluation-order.ts
create-transformer-leak.ts
createRegexDeserializer.js
createRegexSerializer.js
extendLoad.js
ImageryLayerPreloadHelpers.js
invokeTerriaAnalyticsService.js
junk.ts
Pooling.js
SensorObservationServiceRequestTemplate.xml
setClockCurrentTIme.js
Services.js
updateRectangleFromRegion.js
```

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by tephenavies** [comment]
I like this change. I think the grouping you've done is good. Let's get this merged. Even though it's a fairly internal change could you please add a CHANGES.md entry?

**Comment by zoran995** [comment]
added `changes.md` entry and removed above listed unused files

**Comment by nf-s** [comment]
I'm a big fan of this.
A few suggestions:

- move `ItemSearchProvider.ts` to `ItemSearchProviders/ItemSearchProvider.ts`

**Comment by nf-s** [comment]
I'm a big fan of this.

A few suggestions:

.
- move `ItemSearchProvider.ts` to `ItemSearchProviders/ItemSearchProvider.ts`
- `ItemSearchProviders.ts ` to `ItemSearchProviders/ItemSearchProviders.ts`
- All other `SearchProvider` files to `Models/SearchProviders/`
- `SensorObservationServiceRequestTemplate.xml` to `Models/Catalog/Ows`

.
- `SplitItemReference.ts` to `Models/Catalog/
- `UrlReference.ts` to `Models/Catalog/
- `proxyCatalogItemUrl.ts` to `Models/Catalog/`
- `addUserFiles.ts` to  `Models/Catalog/`
- `openGroup.ts` to  `Models/Catalog/`
- `registerCatalogMembers.ts `  to `Models/Catalog/`
- `ResultPendingCatalogItem.ts ` to  `Models/Catalog/`

.
- `Models/Catalog/Ows/WebProcessingService**` to `Models/Catalog/CatalogFunctions

**Comment by zoran995** [comment]
moved the files to their directories as nick suggested, except the `WebProcessingService*` as I am not sure if we will more expect it to be in `catalogFunctions` or next to other `ows` services

**Comment by nf-s** [comment]
Hey @zoran995 - i'm resolving those conflicts, and then i'll merge it.

Thanks for the PR!

**Review by nf-s — APPROVED** [review]

**Pull request merged**
