### PR TITLE
TerriaJsonCatalogFunction

### PR DESCRIPTION
**Pull request by kring**
This builds on #2931 and moves away from the WPS-esque input parameter specification and toward something that I hope is a little cleaner and more succinct.

### CODE REVIEW

**Comment by kring** [comment]
Here's an example JSON file to drive this:

```
{
    "homeCamera": {
        "north": -8,
        "east": 158,
        "south": -45,
        "west": 109
    },
    "corsDomains": [
        "localhost"
    ],
    "catalog": [
        {
            "name": "TESTING",
            "type": "group",
            "isOpen": true,
            "items": [
                {
                    "name": "first test",
                    "type": "terria-json",
                    "url": "https://putsreq.com/PK2GvS6jHfWhlBmkadrG",
                    "inputs": [
                        {
                            "id": "LonLatPosition",
                            "type": "point",
                            "isRequired": true,
                            "name": "Latitude and Longitude",
                            "description": "Select point on map",
                            "formatter": "geoJsonFeature"
                        },
                        {
                            "id": "radius",
                            "type": "string",
                            "isRequired": true,
                            "name": "Radius (in km)"
                        },
                        {
                            "id": "Forestry",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Forestry",
                            "description": "Whether or not to include Forestry data in analysis (under development)"
                        },
                        {
                            "id": "Sugar",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Sugar",
                            "description": "Whether or not to include Sugar data in analysis (under development)",
                            "defaultValue": true
                        },
                        {
                            "id": "Livestock",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Livestock",
                            "description": "Whether or not to include Livestock data in analysis (under development)"
                        },
                        {
                            "id": "Wheat",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Wheat",
                            "description": "Whether or not to include Wheat data in analysis (under development)"
                        },
                        {
                            "id": "Boundary",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Boundary",
                            "description": "Whether or not to include Boundary data in analysis (under development)"
                        },
                        {
                            "id": "Electricity",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Electricity",
                            "description": "Whether or not to include Electricity data in analysis (under development)",
                            "trueName": "Zap",
                            "falseName": "No Zap"
                        },
                        {
                            "id": "Transport",
                            "type": "boolean",
                            "isRequired": false,
                            "name": "Transport",
                            "description": "Whether or not to include Transport data in analysis (under development)"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Same thing available as a gist here: https://gist.github.com/kring/fdd620f1b710a10dfae8fdf14d82b458

Try it out here:
http://ci.terria.io/terria-json-function/#https://gist.githubusercontent.com/kring/fdd620f1b710a10dfae8fdf14d82b458/raw/1c9177eb3feb465698ef873e4b8d5f317cb1c1df/TerriaJsonCatalogFunctionTest.json

And see how the service gets calls here:
https://putsreq.com/PK2GvS6jHfWhlBmkadrG/inspect

**Comment by kring** [comment]
@Jason-DNetto please take a look at see if this still works for your use-case. I'm also interested in any other thoughts you have on the approach.

**Comment by Jason-DNetto** [comment]
mostly works for me. the defaultValue: true does not seem to show up, I never tested defaultValue: true . lib/ReactViews/Analytics/BooleanParameterEditor.jsx references this.props.parameter.value, could that cause defaultValue to not get read.

**Comment by kring** [comment]
Good catch, I'll check that out.

**Pull request merged**
