### PR TITLE
Checkbox fix click event

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #<insert issue number here if relevant>

Checkbox component has wrong placement of label element which results in non-clickable checkbox icon. 

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by steve9164** [comment]
I think this leads to invalid HTML. <label> cannot have <div> nested inside. At least `<Spacing>` would have to be replaced with its `<span>` equivalent (which I think is `<SpacingSpan>`). I haven't looked at the other components to tell if they need to be changed too. Also there should be only 1 control inside the `<label>` (though that should already be correct)

Other than that I think this should work well.

**Review by tephenavies — CHANGES_REQUESTED** [review]
I think this leads to invalid HTML. <label> cannot have <div> nested inside. At least `<Spacing>` would have to be replaced with its `<span>` equivalent (which I think is `<SpacingSpan>`). I haven't looked at the other components to tell if they need to be changed too. Also there should be only 1 control inside the `<label>` (though that should already be correct)

Other than that I think this should work well.

**Comment by zoran995** [comment]
nice catch, fixed. Also updated id so it's not only number

**Comment by tephenavies** [comment]
Waiting on test in #5588 and then I'll merge this and close that PR.

**Pull request merged**
