### PR TITLE
fix missing small screen default size

### PR DESCRIPTION
**Pull request by chloeleichen**

### CODE REVIEW

**Review by soyarsauce — APPROVED** [review]
💯

**Review by soyarsauce — CHANGES_REQUESTED** [review]
Actually this isn't prettier-ed?

**Comment by chloeleichen** [comment]
it is now :D

**Review by soyarsauce — APPROVED** [review]

**Comment by soyarsauce** [comment]
Looks good again 😎 nice rapido fix
Will merge when travis is done

**Pull request merged**
