### PR TITLE
Remove IE overlay

### PR DESCRIPTION
**Pull request by reginapramesti**
### What this PR does

Addresses https://github.com/TerriaJS/terriajs/pull/4820#discussion_r498579625

Removed the IE overlay cause `next` doesn't load on IE anyway

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Review by KeyboardSounds — APPROVED** [review]

**Review by KeyboardSounds — DISMISSED** [review]
Whoops 😬 I'm not sure why I put this there. Could you please remove the InternetExplorerOverlay files as well?

**Comment by reginapramesti** [comment]
@KeyboardSounds it's a result of merging master into next so not actually your doing 😄 I'll remove that file too then

**Comment by tephenavies** [comment]
Sorry @KeyboardSounds. I merged it to `next`. It was a conscious decision to include it as I thought that `gulp release` builds still "worked" (with many CSS issues) but I think now all builds of `next` lead to white screen in IE11.

**Review by soyarsauce — APPROVED** [review]

**Comment by soyarsauce** [comment]
Files removed now

**Comment by soyarsauce** [comment]
Files removed now, and indeed a current reviewer with requested changes will block merging! @KeyboardSounds go ahead 🙂

**Pull request merged**
