### PR TITLE
Add `featureInfoTemplate` to all `Mappable` CatalogItems

### PR DESCRIPTION
**Pull request by nf-s**
### What this PR does

* Rename `FeatureInfoMixin` to `FeatureInfoUrlTemplateMixin`
* Move `featureInfoTemplate` and `showStringIfPropertyValueIsNull` from `FeatureInfoTraits` to `MappableTraits` (all mappable catalog items)
* Remove `FeatureInfoUrlTemplateTraits` from all models that don't use `FeatureInfoUrlTemplateMixin`
  
### Test me
  
Some catalog items with `featureInfoTemplate`

- http://ci.terria.io/refactor-feature-info/#configUrl=https%3A%2F%2Fnationalmap.gov.au%2Fconfig.json&share=s-xTvozhIWmsedgdFv815VACx7hMU
- http://ci.terria.io/refactor-feature-info/#configUrl=https%3A%2F%2Fnationalmap.gov.au%2Fconfig.json&share=s-lhQ91juuFONSd60RfIJUj1VZ71f

### Checklist

-   [ ] ~There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)~ `featureInfoTemplate` tests already exist
-   [ ] ~I've updated relevant documentation in `doc/`.~
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by zoran995** [comment]
ouch, probably will have to revert some of this changes in #5660 😆 (just so I don't have to look why is it not working after rebasing changes 🤣)

**Comment by nf-s** [comment]
Sorry @zoran995 I totally forgot about your PR!
I'll make sure I review it before doing any more on this.

**Review by staffordsmith83 — CHANGES_REQUESTED** [review]
Looks good! But there are still a couple of weak references to FeatureInfoMixin.

https://github.com/TerriaJS/terriajs/blob/5bcc129ed0cc4fd7e197f8754a974ac619951fa6/lib/ModelMixins/FeatureInfoUrlTemplateMixin.ts#L177

And here in a comment: https://github.com/TerriaJS/terriajs/blob/5bcc129ed0cc4fd7e197f8754a974ac619951fa6/lib/Models/Catalog/CatalogItems/OpenDataSoftCatalogItem.ts#L606


Apart from that looks good to me

**Review by staffordsmith83 — APPROVED** [review]
Looks good approved!

**Pull request merged**
