### PR TITLE
upgrade husky to v8

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

husky in v7 changed the way it works internally and it should provide more performant, also the v4 version wasn't running always on my machine most of the times it just skipped it like it wasn't there

### Test me
  
- checkout the branch
- run yarn install
- try some dummy commit that should trigger prettier run and observe that pretty-quick fixed that file

### Checklist

-   ~[ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)~
-   ~[ ] I've updated relevant documentation in `doc/`.~
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Review by nf-s — CHANGES_REQUESTED** [review]
Thanks @zoran995 !

I'm getting `The '.husky/pre-commit' hook was ignored because it's not set as executable` 

is there an easy way to set cross-platform file permissions automatically?

**Comment by zoran995** [comment]
According to the husky docs this should be handled automatically https://typicode.github.io/husky/#/?id=hooks-not-running

Only things that occur to me is that since the pre-commit file is coming from windows it don't have those set up correctly (but if that is case than it is really weird behavior) 
Can you try just to see if above can be source of the problem
```sh
rm .husky/pre-commit
npx husky add .husky/pre-commit "npx pretty-quick --staged"
```

Also one important note for husky v8 is that it requires node 14 or later

**Comment by zoran995** [comment]
@nf-s this should work now (tested on mac)
the fix was to update git index with chmod
```sh
git update-index --chmod=+x .husky/pre-commit
```

force push was just a committer name change so CLAassistant doesn't complain

**Review by nf-s — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
