### PR TITLE
Add support for itemProperties to CswCatalogGroup.

### PR DESCRIPTION
**Pull request by kring**
See discussion in #1365.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
The travis failure looks like not a real failure, just a timeout, right?

**Comment by kring** [comment]
Yep, just Travis being flaky.  I forced it to run again and it was fine.

**Comment by kring** [comment]
It'd be great to have a review of this one too.

**Comment by rsignell-usgs** [comment]
This worked great for me...

**Pull request merged**
