### PR TITLE
Adding ability to dismiss story, popup on remove all stories, 

### LINKED ISSUE #3537: Story: v1.1 - make it easier to dismiss the Story panel
**Feedback:**
> it is not intuitive to click on Story button again to close the story workbench.
> All top menu buttons have the X for closing them.

Expanding and collapsing/dismissing elements in Terria should be consistent and intuitive across the platform. Currently the Story panel behaves like a contextual menu (map, share), but is more closely related to the data workbench. This is a bit confusing, and could potentially be resolved by applying a show/hide tab to the Story panel.

### PR DESCRIPTION
**Pull request by zoran995**
Resolves some story issue and adding new abilities
- [x] error in console with a shared story when user click Maybe Later (haven't see that this was reported)
- [x] make it easier to dismiss story panel, resolves #3537 
- [x] check if the user is sure that he wants to close a window if there are stories (using browser default beforeUnload) #3539
- [x] added story share option (the share panel is the same as in other parts of the application) #3539
- [x] long story title overlap with the option button

story-panel  remove-all  story-share

@vicborgy @alyce any opinions on this

### CODE REVIEW

**Comment by soyarsauce** [comment]
To be reviewed by UX after 20th

**Comment by tephenavies** [comment]
Available for testing at http://ci.terria.io/zoran995-story-panel/

**Comment by vicborgy** [comment]
Here are the latest designs for Stories. The work from Zoran was heading down the right track but felt it lacked a little continuity from the visuals I've since completed for Onboarding and Delta. https://invis.io/KTWPRT8CM82

**Comment by soyarsauce** [comment]
Hey @vicborgy - thanks for the new story design. I understand you're doing this for continuity of visuals with the new mobx styles, however this PR is for master. Would it be ok for Zoran to update this PR with the _new layout_ you have showing in invision, but using the _current master styling language_? For instance,
- no new rounded buttons
- keeping the old "BadgeBar" style in master
image

Finally, your prototype doesn't seem to include a way of confirmation-of-dismissing-all which this PR is trying to address. Only confirmation-of-deleting-individual-stories. Can we similarly, apply your confirmation dialog to the "remove all" action?

**Comment by vicborgy** [comment]
Leave it with me. and I'll tweak it for master. It would be good to edit a few other bits.

**Comment by vicborgy** [comment]
Here is what im thinking.
Stories Master

**Review by soyarsauce — DISMISSED** [review]
Hi @zoran995 
We've got both https://github.com/TerriaJS/terriajs/pull/3938#issuecomment-609525972 && https://github.com/TerriaJS/terriajs/pull/3938#issuecomment-609542876 for you to do a few small tweaks with, then an entry to `CHANGES.md`, and then let's get this merged! Again noting we are focusing all our efforts on the mobx branch right now. Thanks!

**Comment by zoran995** [comment]
I think this is ready now.
I will try to focus on mobx as soon as possible, I have a few things that are developed for master (drawing tool, new functionalities in measurement tool) that I will have to rewrite for mobx.
Just one side note for remove panel I think it should also be introduced for workbench items (don't know, maybe it is already in @vicborgy designs for that part).

**Review by tephenavies — APPROVED** [review]

**Pull request merged**
