### PR TITLE
Generate legends as SVG instead of PNG

### PR DESCRIPTION
**Pull request by stevage**

### CODE REVIEW

**Comment by kring** [comment]
The new legends don't show up in in Firefox, IE11, or Edge.

In IE11 and Edge, the URL is listed as `data:image/svg+xml,undefined` so it seems like something is going wrong in the SVG generation process?

In Firefox, there's some SVG XML there, but Firefox reports "XML Parsing Error: unclosed token".

**Comment by stevage** [comment]
Looks like my change embedding the svg directly also fixed FireFox.

**Comment by stevage** [comment]
[This URL](http://localhost:3001/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%22init%2Ftest.json%22%2C%7B%22sharedCatalogMembers%22%3A%7B%22Root%20Group%2FNational%20Data%20Sets%2FElevation%2FCuttings%22%3A%7B%22name%22%3A%22Cuttings%22%2C%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22type%22%3A%22esri-mapServer%22%2C%22id%22%3A%22Root%20Group%2FNational%20Data%20Sets%2FElevation%2FCuttings%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FNational%20Data%20Sets%22%2C%22Root%20Group%2FNational%20Data%20Sets%2FElevation%22%5D%7D%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FEmergency%2FDisasterManagementStormtideFlood_SCRC%2FStormtide%20flood%20model%20extent%20Sept%202012%22%3A%7B%22name%22%3A%22Stormtide%20flood%20model%20extent%20Sept%202012%22%2C%22nowViewingIndex%22%3A3%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22type%22%3A%22esri-mapServer%22%2C%22id%22%3A%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FEmergency%2FDisasterManagementStormtideFlood_SCRC%2FStormtide%20flood%20model%20extent%20Sept%202012%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FData%20Providers%22%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%22%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FEmergency%22%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FEmergency%2FDisasterManagementStormtideFlood_SCRC%22%5D%7D%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FInlandWaters%2FInlandWaters_SCRC%2FWater%20Bodies%22%3A%7B%22name%22%3A%22Water%20Bodies%22%2C%22nowViewingIndex%22%3A2%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22type%22%3A%22esri-mapServer%22%2C%22id%22%3A%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FInlandWaters%2FInlandWaters_SCRC%2FWater%20Bodies%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FData%20Providers%22%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%22%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FInlandWaters%22%2C%22Root%20Group%2FData%20Providers%2FSunshine%20Coast%20Council%20%28QLD%29%2FInlandWaters%2FInlandWaters_SCRC%22%5D%7D%2C%22Root%20Group%2FTerriaJS%20test%20data%2FCsv-geo-au%2FGreater%20capital%20city%20statistical%20area%20%28GCCSA%29%22%3A%7B%22name%22%3A%22Greater%20capital%20city%20statistical%20area%20%28GCCSA%29%22%2C%22nowViewingIndex%22%3A1%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22Urban%22%2C%22scale%22%3A1%2C%22colorBins%22%3A7%2C%22colorBinMethod%22%3A%22auto%22%2C%22legendTicks%22%3A3%7D%2C%22type%22%3A%22csv%22%2C%22id%22%3A%22Root%20Group%2FTerriaJS%20test%20data%2FCsv-geo-au%2FGreater%20capital%20city%20statistical%20area%20%28GCCSA%29%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FTerriaJS%20test%20data%22%2C%22Root%20Group%2FTerriaJS%20test%20data%2FCsv-geo-au%22%5D%7D%7D%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A85.60546875%2C%22south%22%3A-54.059387886623576%2C%22east%22%3A181.40625%2C%22north%22%3A5.965753671065524%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Dark%20Matter%22%2C%22viewerMode%22%3A%222d%22%7D%5D%7D&activeTabId=NowViewing) is what I'm using for testing.

**Comment by kring** [comment]
In Firefox, the legend now shows up correctly on the Now Viewing.  However, when I click it, I get:
image

**Comment by kring** [comment]
In IE and Edge, the legend doesn't show up because the `outerHTML` property is not supported on SVG elements.  A possible (but ugly) workaround is to copy all of the elements inside the SVG to a div, and then use innerHTML.

**Pull request merged**
