### PR TITLE
Update GoogleAnalytics to use GA4

### PR DESCRIPTION
**Pull request by tephenavies**
### What this PR does

Switch over to using `react-ga4` package to handle Google Analytics. This will allow us to collect events in GA4 properties.

### Test me

Build locally and test with a GA4 property id.

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by t83714** [comment]
@steve9164 Is there an easier way to turn on google analytics in the CI deployment site?
Currently, CI site `http://ci.terria.io/ga4/` print out the following in console:
```
ConsoleAnalytics was started, however `configParameters.enableConsoleAnalytics` was not defined or set to false.
```

**Comment by tephenavies** [comment]
Once the build is finished, http://ci.terria.io/ga4 should allow testing GA4 if you put a breakpoint into GoogleAnalytics.ts and modify `this.key` before `initializeGoogleAnalytics(this);` is called.


**Before merging**:
- [x] Revert `fb2bfe17ecf`
- [x] [Delete`test-ga4-ci` branch in TerriaMap](https://github.com/TerriaJS/TerriaMap/branches)

**Review by t83714 — COMMENTED** [review]
tested with https://tagassistant.google.com/
Randomly test some events and seems event sending ok --- see screenshot below

CleanShot 2023-06-28 at 08 56 32@2x

CleanShot 2023-06-28 at 08 56 50@2x

**Add from catalogue:**
CleanShot 2023-06-28 at 08 57 06@2x

**Remove from workbench:**
CleanShot 2023-06-28 at 08 57 36@2x

**Zoom in:**

CleanShot 2023-06-28 at 08 57 59@2x


**Zoom Out:**

CleanShot 2023-06-28 at 08 58 17@2x

**The only issue is the pageview trigger:**
GA 4 has a built-in new feature (on google side) will auto-monitor the event listener and send event.
This will make page_view send twice.
To fix it, we need to do 2 things:
- 1> initialise the tracker with `send_page_view: false`
```javascript
const trackers = gapiIds.map((trackingId) => ({
    trackingId: trackingId,
    gtagOptions: {
        send_page_view: false
    }
}));
```
- 2> turn off the feature from google analytics side turn off auto page_view sent
Data Streams 

CleanShot 2023-06-28 at 10 35 55

CleanShot 2023-06-28 at 10 36 39

**Comment by t83714** [comment]
Alternatively, as we don't do too much routing in terriajs, we can also rely on GA v4's auto page_view event --- i.e we don't send page_view in our code.
But I guess we highly likely don't want to rely on GAv4's event, as when we implement more routing, we will want to control more of the page_view by ourselves.

**Comment by tephenavies** [comment]
- [x] Tested to ensure double page views have stopped.

**Review by t83714 — APPROVED** [review]
tested and can confirm only one page_view event will be sent 🎉 
CleanShot 2023-06-28 at 13 07 41@2x
I think the PR it's ready to go now~

**Pull request merged**
