### PR TITLE
Add getAncestors contract

### PR DESCRIPTION
**Pull request by soyarsauce**
### What this PR does

Stops terriajs from breaking https://github.com/TerriaJS/terrace/issues/116 

### Checklist

-   [X] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by soyarsauce** [comment]
GH just didn't get status updated with api - both build jobs pass

**Review by rowanwins — CHANGES_REQUESTED** [review]
This is a pretty abstract test - can we add some code comments around when this occurs and the expected behaviour?

**Comment by soyarsauce** [comment]
@rowanwins  The tests map almost 1 to 1 with the code comments in https://github.com/TerriaJS/terriajs/blob/083ab51eb0456d8e6512e49202b9234706324f74/lib/Models/getAncestors.ts#L4
But yes can do for extra information - have just added some extra to https://github.com/TerriaJS/terriajs/pull/4395/commits/083ab51eb0456d8e6512e49202b9234706324f74#diff-1adc935206ca05f402b814f5cf908194R29

**Review by rowanwins — APPROVED** [review]
Thanks for adding those comments, knowing there are comments in the src helps!

**Pull request merged**
