### PR TITLE
Update to svg-sprite-loader 3

### PR DESCRIPTION
**Pull request by tephenavies**
Closes #2558.

### CODE REVIEW

**Comment by tephenavies** [comment]
The examples say to use `o.viewBox` in the viewBox property and `'#' + o.id` for the id, but our svgs seem to be made to work with a hardcoded "0 0 100 100" viewBox.

This is completely broken on IE. Anyone with IE keen to take a look 😃 ?

**Comment by kring** [comment]
> This is completely broken on IE. Anyone with IE keen to take a look 😃 ?

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
😛

**Comment by tephenavies** [comment]
image

Ok.

**Comment by tephenavies** [comment]
Fixed!

**Pull request merged**
