### PR TITLE
Upgrade protomaps and use it for region mapping

### PR DESCRIPTION
**Pull request by tephenavies**
### What this PR does

Upgrading protomaps to support compressed tiles, pmtiles archive version 3 and using protomaps renderer for region mapping.

- [ ] Remove MapboxVectorTileImageryProvider
- [ ] Update ProtomapsImageryProvider to accept a feature info function similar to https://github.com/TerriaJS/terriajs/blob/40d6f992317a703922440502dd0d803ee559d58a/lib/Table/createRegionMappedImageryProvider.ts#L183-L239

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by AnaBelgun** [comment]
Update 15 March: 
- testing before PR review and merge

**Comment by tephenavies** [comment]
Doesn't work with feature information properly yet. CSV values are missing from the table but vector tile attributes are making it through.

**Comment by AnaBelgun** [comment]
@steve9164 check this https://github.com/TerriaJS/terriajs/pull/7144 / talk to @nf-s

**Comment by nf-s** [comment]
Bumped into https://github.com/TerriaJS/terriajs/pull/7144

**Pull request closed without merging**
