### PR TITLE
Mobx dragdrop file fix

### LINKED ISSUE #4102: Model Architecture: Drag and drop
UI for drag and drop is either broken or not yet ported to mobx.

### PR DESCRIPTION
**Pull request by nf-s**
### Fix file drag and drop, and fix "auto" file type resolving 

Fixes #4102

I have fixed drag and drop, and 'auto' file type resolving

### Checklist

-   [x] Make auto file type work
-   [x] ~Discuss if we should refactor the whole CreateCatalogItemFromFileOrUrl... thing~ This can be discussed at a later stage
-   [x] ~Refactor if needed~
-   [x] Add test for 'auto' file type
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by na9da** [comment]
@nf-s Merging from the `mobx` branch should fix the CI errors.

**Comment by nf-s** [comment]
will do, thanks!

**Comment by rowanwins** [comment]
You've got prettier errors @nf-s so another update required :)

It turns out husky (which should auto-run prettier for you when you commit code) only works well with certain versions of node so you might need to just double check that.

**Comment by nf-s** [comment]
Drag dropping in CSVs now works.

**Changes:**
- Mobxified `DragDropFile` and `DragDropNotification` 
- `sourceReference` not being passed through the `CsvCatalogItem`'s constructor. A Developer error was being thrown but was not printed to console for some reason (and the error's stack trace was not useful).
- Change `CsvCatalogItem`'s `forceLoadTableData` to load csvFiles before urls (I'm not sure of wider implications of doing this)
- Renamed `createCatalogItemFromUrl` to `createUrlReferenceFromUrl` to clear confusion between `createCatalogItemFromUrl` and `createCatalogItemFromFileOrUrl`
- After the `UrlReference` has been created in `createCatalogItemFromFileOrUrl`, the `target` is checked for `hasFileInput` (recursively)

**The whole thing is a bit messy, but I'm not sure how to clean it up at this point:**

- Maybe create a FileInputMixin or LocalDataMixin
- Or add some sort of fileInput to `UrlReference`
- The whole `isUrl` and `allowLoad` thing is confusing
- Should there be some separation of URL sources and file sources?

**Comment by nf-s** [comment]
I'm not sure why `1) changes cursor to crosshair when entering drawing mode - UserDrawing that requires WebGL` test is failing

**Comment by nf-s** [comment]
Urgh - a test error:

> should create an catalog item (CSVCatalogItem) from File (csv) without specifying a dataType
> `ReferenceError: 'fetch' is undefined`

I love IE

**Review by KeyboardSounds — APPROVED** [review]

**Pull request merged**
