### PR TITLE
css fixes

### PR DESCRIPTION
**Pull request by chloeleichen**
Some css fixes for https://github.com/TerriaJS/terriajs/issues/2048

### CODE REVIEW

**Comment by RacingTadpole** [comment]
This has a few strange effects I'm afraid! The Run Analysis button has moved, and the info text size is bigger:
image

**Comment by rdengate** [comment]
@chloeleichen if you're looking at the position of the "Run Analysis" button, it'd be great if you could consider https://github.com/TerriaJS/terriajs/issues/2055 also :-)

**Comment by chloeleichen** [comment]
@rdengate this PR will fix that, too

**Comment by rdengate** [comment]
awesome, thanks @chloeleichen!

**Review by RacingTadpole — CHANGES_REQUESTED** [review]
Just trying out github's new review feature. :-) Can you take a look at my comment above?

**Comment by chloeleichen** [comment]
@RacingTadpole I moved the run analysis button to be consistent with the add to the map and avoid multiple scrolling bar and other complexities. 

Fixed the font size inconsistency.

**Comment by RacingTadpole** [comment]
Cool! I'm being pedantic now but two last things 
- the font of the lat/lon is very small
- the height of the lat/lon box looks a little higher (and wider) than eg. the date box - is that intentional?
  image

**Comment by RacingTadpole** [comment]
Also can we get a UX opinion on `Run Analysis` now being in the top right @philipgrimmett ?  To me it's less clear than at the bottom (eg. most forms get submitted by a button at the bottom, not at the top).

**Comment by chloeleichen** [comment]
sure let me run that through phil phil phil

**Pull request closed without merging**
